// Generated by Google Stitch. Source folder: 22-guest_messaging
//
// ── ⚠ GUARDED 9 August 2026, BEFORE BUILD 9. ───────────────────────────────
//
// This screen used to show three invented guest conversations — "Sarah
// Jenkins", "Marcus Thorne" and "The Millers" — each with a property name, a
// truncated message, a stock Unsplash portrait, and an unread badge.
//
// It is reachable: host_01_dashboard_screen routes its fourth nav destination
// here. So a host opened Messages, saw three people who do not exist appearing
// to wait on a reply, tapped one, and nothing happened.
//
// Less dangerous than the fabricated money on screen 20, but the same class of
// fault: invented content presented as the host's own data. An unread badge is
// a claim that someone is waiting for you.
//
// Messaging has no backend. There is no messages collection, no rule for one,
// and no Cloud Function. Until that exists this screen says so.
//
// The fake list and its helpers are deleted, not commented out.
//
// WHEN MESSAGING IS BUILT: it needs a /stay_messages collection scoped to
// booking id, firestore.rules allowing only the booking's guest and host to
// read or write, and a decision on retention — guest contact details are
// personal data and the privacy policy must cover them before launch.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';

import 'host_bottom_nav.dart';
import 'host_routes.dart';

class GuestMessagingScreen extends StatelessWidget {
  const GuestMessagingScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Messages',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
        // The avatar that sat here was a stock Unsplash photograph of a
        // stranger, presented as the host's own account picture. Removed.
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            const SizedBox(height: 24),
            Center(
              child: Container(
                width: 72,
                height: 72,
                decoration: const BoxDecoration(
                  color: GoOutsColors.tint,
                  shape: BoxShape.circle,
                ),
                child: const Icon(Icons.forum_outlined,
                    size: 34, color: GoOutsColors.primary),
              ),
            ),
            const SizedBox(height: 24),
            Text(
              'Messaging is not open yet',
              style: GoogleFonts.inter(
                color: GoOutsColors.navy,
                fontSize: 20,
                fontWeight: FontWeight.w800,
                height: 1.3,
              ),
            ),
            const SizedBox(height: 12),
            Text(
              'In-app messaging between you and your guests has not been built '
              'yet. Nothing is being sent to you here, and nothing you write '
              'here would reach anyone.',
              style: GoogleFonts.inter(
                color: GoOutsColors.body,
                fontSize: 14,
                height: 1.55,
              ),
            ),
            const SizedBox(height: 24),
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: GoOutsColors.infoBg,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(
                    color: GoOutsColors.primary.withValues(alpha: 0.25)),
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  const Icon(Icons.info_outline_rounded,
                      size: 18, color: GoOutsColors.primary),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      'Booking requests are where your guests reach you for '
                      'now. Accepting or declining a request tells the guest '
                      'straight away.',
                      style: GoogleFonts.inter(
                        color: GoOutsColors.body,
                        fontSize: 13.5,
                        height: 1.5,
                      ),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 20),
            OutlinedButton.icon(
              onPressed: () =>
                  Navigator.of(context).pushNamed(HostRoutes.requests),
              icon: const Icon(Icons.calendar_month_outlined, size: 18),
              label: const Text('Go to booking requests'),
              style: OutlinedButton.styleFrom(
                minimumSize: const Size(double.infinity, 50),
                foregroundColor: GoOutsColors.primary,
                side: const BorderSide(color: GoOutsColors.primary),
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12)),
              ),
            ),
            const SizedBox(height: 32),
          ],
        ),
      ),
      // The compose FloatingActionButton had an empty onPressed. A button that
      // opens nothing is worse than no button — removed until there is
      // something to compose.
      bottomNavigationBar: const HostBottomNav(current: HostTab.bookings),
    );
  }
}
