// Generated by Google Stitch. Source folder: 6-photo_upload
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import 'host_routes.dart';

import '../../../theme/goouts_colors.dart';


class PhotoUploadScreen extends StatefulWidget {
  const PhotoUploadScreen({super.key});

  @override
  State<PhotoUploadScreen> createState() => _PhotoUploadScreenState();
}

class _PhotoUploadScreenState extends State<PhotoUploadScreen> {
  final List<String> _photos = [
    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800',
    'https://images.unsplash.com/photo-1556911223-e27021882721?auto=format&fit=crop&q=80&w=800',
    'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800',
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          // Was `leading: const Icon(...)` — a decorative arrow that
          // was NOT tappable. It looked like a back button and did
          // nothing, which is worse than having no arrow at all.
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Create Listing',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
        actions: [
          TextButton(
            onPressed: () {},
            child: Text(
              'Save & Exit',
              style: GoogleFonts.inter(
                color: GoOutsColors.primary,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          const SizedBox(width: 8),
        ],
      ),
      body: Column(
        children: [
          _buildProgressBar(),
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Add some photos of your property',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 24,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'You\'ll need 5 photos to get started. You can add more or make changes later.',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.body,
                      fontSize: 15,
                    ),
                  ),
                  const SizedBox(height: 24),
                  _buildAuthenticityWarning(),
                  const SizedBox(height: 32),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        'Gallery',
                        style: GoogleFonts.inter(
                          color: GoOutsColors.navy,
                          fontSize: 18,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                        decoration: BoxDecoration(
                          color: GoOutsColors.primary.withValues(alpha: 0.1),
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: Text(
                          '${_photos.length} / 5 minimum',
                          style: GoogleFonts.inter(
                            color: GoOutsColors.primary,
                            fontSize: 12,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),
                  _buildPhotoGrid(),
                  const SizedBox(height: 40),
                ],
              ),
            ),
          ),
          _buildFooter(),
        ],
      ),
    );
  }

  Widget _buildProgressBar() {
    return Container(
      width: double.infinity,
      height: 4,
      color: GoOutsColors.primary.withValues(alpha: 0.1),
      child: FractionallySizedBox(
        alignment: Alignment.centerLeft,
        widthFactor: 0.8, // Step 4 of 5
        child: Container(color: GoOutsColors.primary),
      ),
    );
  }

  Widget _buildAuthenticityWarning() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: GoOutsColors.warningBg,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: GoOutsColors.error.withValues(alpha: 0.1)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.warning_amber_rounded, color: GoOutsColors.warningText, size: 24),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Authenticity Warning',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.warningText,
                    fontSize: 15,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'Use your own photographs of this property. Do not use images from anywhere else, and do not use generated or heavily edited images.',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.warningText.withValues(alpha: 0.8),
                    fontSize: 14,
                    height: 1.4,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPhotoGrid() {
    return Column(
      children: [
        if (_photos.isNotEmpty) _buildMainPhoto(_photos[0]),
        const SizedBox(height: 12),
        GridView.builder(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
            crossAxisSpacing: 12,
            mainAxisSpacing: 12,
            childAspectRatio: 1,
          ),
          itemCount: _photos.length > 1 ? _photos.length : 1, // At least show placeholder if only 1 photo
          itemBuilder: (context, index) {
            if (index == 0 && _photos.isNotEmpty) {
               // Skip first photo as it's the main hero above
               return _photos.length > 1 ? _buildSecondaryPhoto(_photos[1]) : _buildAddPhotoPlaceholder();
            }
            if (index < _photos.length) {
              return _buildSecondaryPhoto(_photos[index]);
            }
            return _buildAddPhotoPlaceholder();
          },
        ),
        const SizedBox(height: 12),
        // If we have more than 2 photos, show the remaining add placeholder
        if (_photos.length >= 2) _buildAddPhotoPlaceholder(),
      ],
    );
  }

  Widget _buildMainPhoto(String url) {
    return Stack(
      children: [
        ClipRRect(
          borderRadius: BorderRadius.circular(16),
          child: Image.network(
            url,
            height: 240,
            width: double.infinity,
            fit: BoxFit.cover,
          ),
        ),
        Positioned(
          top: 12,
          left: 12,
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(8),
              boxShadow: [BoxShadow(color: Colors.black.withValues(alpha: 0.1), blurRadius: 4)],
            ),
            child: Row(
              children: [
                const Icon(Icons.star, color: GoOutsColors.primary, size: 16),
                const SizedBox(width: 4),
                Text(
                  'Cover Photo',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 12,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildSecondaryPhoto(String url) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(16),
      child: Image.network(
        url,
        fit: BoxFit.cover,
      ),
    );
  }

  Widget _buildAddPhotoPlaceholder() {
    return Container(
      height: 160,
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: GoOutsColors.primary.withValues(alpha: 0.2),
          width: 2,
          style: BorderStyle.none, // In Flutter we use DottedBorder package for this usually
        ),
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: GoOutsColors.primary.withValues(alpha: 0.1),
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.add_photo_alternate_outlined, color: GoOutsColors.primary, size: 32),
          ),
          const SizedBox(height: 12),
          Text(
            'Add Photos',
            style: GoogleFonts.inter(
              color: GoOutsColors.teal,
              fontSize: 15,
              fontWeight: FontWeight.w700,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildFooter() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: const BoxDecoration(
        color: GoOutsColors.surface,
        border: Border(top: BorderSide(color: Colors.black12, width: 0.5)),
      ),
      child: SafeArea(
        child: Row(
          children: [
            TextButton(
              onPressed: () {},
              child: Text(
                'Back',
                style: GoogleFonts.inter(
                  color: GoOutsColors.navy,
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
            const Spacer(),
            ElevatedButton(
              onPressed: () =>
                  Navigator.of(context).pushNamed(HostRoutes.newPricing),
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF00668C),
                minimumSize: const Size(160, 52),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                elevation: 0,
              ),
              child: Text(
                'Next Step',
                style: GoogleFonts.inter(
                  color: Colors.white,
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
