// Generated by Google Stitch. Source folder: 8-Legal & Compliance
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// WIRED 6 August 2026. This is the LAST step of the listing wizard and the
// screen that actually creates the listing, via createStayListing.
//
// The three checkboxes are not decoration. All three must be true or the
// server refuses, and the answers are stored on the listing with a SERVER
// timestamp — a device clock is set by the person making the legal statement.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import 'host_routes.dart';
import 'listing_draft.dart';

import '../../../theme/goouts_colors.dart';
import 'friendly_error.dart';


class LegalComplianceScreen extends StatefulWidget {
  const LegalComplianceScreen({super.key});

  @override
  State<LegalComplianceScreen> createState() => _LegalComplianceScreenState();
}

class _LegalComplianceScreenState extends State<LegalComplianceScreen> {
  bool _mortgagePermit = false;
  bool _safetyDuty = false;
  bool _nightLimitAwareness = false;
  bool _submitting = false;

  // ───────────────────────────────────────────────────────────────────────────
  //  THE END OF THE WIZARD. This is where the listing is actually created.
  //
  //  Continue used to push straight to payout details, which meant a host
  //  completed eight steps, ticked three legal warranties, and NOTHING WAS
  //  EVER WRITTEN. They finished with no listing and no error.
  //
  //  Submitting here rather than after payout is deliberate: payout details
  //  cannot be saved at all yet (see screen 09), so a host who stopped at that
  //  screen would still lose everything. The property is the thing worth
  //  keeping, and it is complete by this point.
  // ───────────────────────────────────────────────────────────────────────────
  Future<void> _submit() async {
    final d = ListingDraft.instance;
    d
      ..mortgagePermit = _mortgagePermit
      ..safetyDuty = _safetyDuty
      ..nightLimitAwareness = _nightLimitAwareness;

    // The server refuses an incomplete address, but failing here means the
    // host is told which screen to go back to rather than getting a generic
    // server error at the very end of an eight step form.
    if (!d.addressComplete) {
      _say('Go back to the address step — the property address is incomplete.',
          isError: true);
      return;
    }
    if (d.nightlyRatePence < 100) {
      _say('Go back to the pricing step and set a nightly rate.',
          isError: true);
      return;
    }

    setState(() => _submitting = true);
    try {
      final id = await d.submit();
      if (!mounted) return;
      if (id.isEmpty) throw Exception('no id returned');

      // Says DRAFT, not "live". A host who thinks their property is bookable
      // when it is awaiting review will wonder why no bookings arrive.
      _say('Saved. Your property will be reviewed before guests can see it.');
      Navigator.of(context).pushNamedAndRemoveUntil(
        HostRoutes.myListings,
        // Clears the eight wizard screens. Without this, Back walks the host
        // through the form they have just completed, on a draft that already
        // exists — and a second submit would create a duplicate listing.
        (route) => route.settings.name == HostRoutes.dashboard,
      );
    } catch (e) {
      // Was e.toString() with a substring — which printed the whole Dart stack
      // trace on screen under the message. See friendly_error.dart.
      if (!mounted) return;
      _say(
          friendlyError(e,
              fallback: 'Could not save your property. Check your connection '
                  'and try again.'),
          isError: true);
    } finally {
      if (mounted) setState(() => _submitting = false);
    }
  }

  void _say(String m, {bool isError = false}) {
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
      content: Text(m),
      backgroundColor:
          isError ? const Color(0xFFDC2626) : const Color(0xFF16A34A),
    ));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.teal),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'A few legal things',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildStepIndicator(),
            Padding(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildRegulatorySection(),
                  const SizedBox(height: 24),
                  _buildChecklistSection(),
                  const SizedBox(height: 24),
                  _buildResponsibilityDisclaimer(),
                  const SizedBox(height: 40),
                ],
              ),
            ),
          ],
        ),
      ),
      bottomNavigationBar: _buildBottomNav(),
    );
  }

  Widget _buildStepIndicator() {
    return Container(
      padding: const EdgeInsets.fromLTRB(16, 20, 16, 12),
      color: GoOutsColors.surface,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Step 4 of 4',
                style: GoogleFonts.inter(
                  color: GoOutsColors.body,
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                ),
              ),
              Text(
                'Registration & Safety',
                style: GoogleFonts.inter(
                  color: GoOutsColors.teal,
                  fontSize: 13,
                  fontWeight: FontWeight.w700,
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          ClipRRect(
            borderRadius: BorderRadius.circular(2),
            child: const LinearProgressIndicator(
              value: 1.0,
              backgroundColor: Color(0xFFDCE6FF),
              valueColor: AlwaysStoppedAnimation<Color>(GoOutsColors.teal),
              minHeight: 4,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildRegulatorySection() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.assignment_outlined, color: GoOutsColors.teal, size: 24),
              const SizedBox(width: 12),
              Text(
                'Regulatory Registration',
                style: GoogleFonts.inter(
                  color: GoOutsColors.navy,
                  fontSize: 16,
                  fontWeight: FontWeight.w700,
                ),
              ),
            ],
          ),
          const SizedBox(height: 20),
          Text(
            'Registration or licence number',
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 14,
              fontWeight: FontWeight.w600,
            ),
          ),
          const SizedBox(height: 8),
          TextField(
            decoration: InputDecoration(
              hintText: 'Enter your number',
              hintStyle: GoogleFonts.inter(color: GoOutsColors.body.withValues(alpha: 0.5)),
              filled: true,
              fillColor: const Color(0xFFF8FAFC),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: GoOutsColors.border),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: GoOutsColors.border),
              ),
              contentPadding: const EdgeInsets.all(16),
            ),
          ),
          const SizedBox(height: 16),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: const Color(0xFFF0F7FF),
              borderRadius: BorderRadius.circular(12),
              border: const Border(left: BorderSide(color: GoOutsColors.teal, width: 4)),
            ),
            child: Text(
              'Note: Registration requirements vary across England, Scotland, Wales, and Northern Ireland. Please ensure you comply with your specific regional mandate.',
              style: GoogleFonts.inter(
                color: GoOutsColors.navy,
                fontSize: 13,
                height: 1.4,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildChecklistSection() {
    return Column(
      children: [
        _buildCheckItem(
          'Mortgage, lease, and insurance permits',
          'I confirm that my mortgage agreement, property lease, and insurance policy explicitly allow for short-term letting of this property.',
          _mortgagePermit,
          (val) => setState(() => _mortgagePermit = val!),
        ),
        const SizedBox(height: 12),
        _buildCheckItem(
          'Gas, electrical, and fire safety',
          'I have fulfilled all legal duties regarding gas safety certificates, electrical inspections, smoke alarms, and fire risk assessments.',
          _safetyDuty,
          (val) => setState(() => _safetyDuty = val!),
        ),
        const SizedBox(height: 12),
        _buildCheckItem(
          'Local night limits awareness',
          'I am aware of and will comply with any local restrictions on the number of nights per year this property can be let out (e.g., the 90-day rule in London).',
          _nightLimitAwareness,
          (val) => setState(() => _nightLimitAwareness = val!),
        ),
      ],
    );
  }

  Widget _buildCheckItem(String title, String subtitle, bool value, Function(bool?) onChanged) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 24,
            height: 24,
            child: Checkbox(
              value: value,
              onChanged: onChanged,
              activeColor: GoOutsColors.teal,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
            ),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 15,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  subtitle,
                  style: GoogleFonts.inter(
                    color: GoOutsColors.body,
                    fontSize: 13,
                    height: 1.4,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildResponsibilityDisclaimer() {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Icon(Icons.info_outline, color: GoOutsColors.body, size: 20),
        const SizedBox(width: 12),
        Expanded(
          child: Text(
            'Please note that these legal and safety requirements are your responsibility rather than ours. We provide this checklist as a guide to help you stay compliant with UK regulations.',
            style: GoogleFonts.inter(
              color: GoOutsColors.body.withValues(alpha: 0.7),
              fontSize: 12,
              height: 1.4,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildBottomNav() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: const BoxDecoration(
        color: GoOutsColors.surface,
        border: Border(top: BorderSide(color: Color(0xFFF1F5F9), width: 1)),
      ),
      child: SafeArea(
        child: ElevatedButton(
          // The guard is Stitch's and it is CORRECT — Continue stays disabled
          // until the host has confirmed all three warranties. Do not
          // remove it to make testing easier; it is the compliance gate.
          onPressed: (_mortgagePermit && _safetyDuty && _nightLimitAwareness &&
                  !_submitting)
              ? _submit
              : null,
          style: ElevatedButton.styleFrom(
            backgroundColor: GoOutsColors.teal,
            disabledBackgroundColor: const Color(0xFFCBD5E1),
            minimumSize: const Size(double.infinity, 56),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            elevation: 0,
          ),
          child: _submitting
              // The label says what the button DOES. "Continue" implied
              // another form step; this is the one that creates the listing.
              ? const SizedBox(
                  width: 22,
                  height: 22,
                  child: CircularProgressIndicator(
                      strokeWidth: 2, color: Colors.white))
              : Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text(
                      'Save my property',
                      style: GoogleFonts.inter(
                        color: Colors.white,
                        fontSize: 16,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                    const SizedBox(width: 8),
                    const Icon(Icons.check, color: Colors.white, size: 20),
                  ],
                ),
        ),
      ),
    );
  }
}
