// Generated by Google Stitch. Source folder: 14-pricing_alert
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';

import 'host_bottom_nav.dart';


class PricingAlertScreen extends StatelessWidget {
  const PricingAlertScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.navy),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Dashboard',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.notifications_outlined, color: GoOutsColors.navy),
            onPressed: () {},
          ),
        ],
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildDemandAlertCard(),
            _buildNearbyActivitySection(),
          ],
        ),
      ),
      bottomNavigationBar: const HostBottomNav(current: HostTab.listings),
    );
  }

  Widget _buildDemandAlertCard() {
    return Container(
      margin: const EdgeInsets.all(16),
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: GoOutsColors.primary.withValues(alpha: 0.1)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.bolt, color: GoOutsColors.primary, size: 16),
              const SizedBox(width: 4),
              Text(
                'DEMAND ALERT',
                style: GoogleFonts.inter(
                  color: GoOutsColors.primary,
                  fontSize: 12,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 0.5,
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            'Something is on near you',
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 22,
              fontWeight: FontWeight.w800,
            ),
          ),
          const SizedBox(height: 20),
          _buildEventInfo(),
          const SizedBox(height: 16),
          Row(
            children: [
              Expanded(child: _buildInfoBit('Venue', 'Sheldonian\nTheatre')),
              const SizedBox(width: 12),
              Expanded(child: _buildInfoBit('Distance', '1.2 miles away')),
            ],
          ),
          const SizedBox(height: 20),
          _buildDemandDetectionCard(),
          const SizedBox(height: 20),
          ElevatedButton(
            onPressed: () {},
            style: ElevatedButton.styleFrom(
              backgroundColor: GoOutsColors.alertBg,
              minimumSize: const Size(double.infinity, 56),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              elevation: 0,
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  'Review my pricing',
                  style: GoogleFonts.inter(
                    color: Colors.white,
                    fontSize: 16,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const SizedBox(width: 8),
                const Icon(Icons.chevron_right, color: Colors.white, size: 20),
              ],
            ),
          ),
          const SizedBox(height: 16),
          Center(
            child: Text(
              'GoOuts suggests prices based on local demand.\nYou set your own rates.',
              textAlign: TextAlign.center,
              style: GoogleFonts.inter(
                color: GoOutsColors.onSurfaceVariant,
                fontSize: 12,
                height: 1.4,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildEventInfo() {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: const Color(0xFFF0F7FF),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(10),
            decoration: const BoxDecoration(
              color: GoOutsColors.primary,
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.calendar_month, color: Colors.white, size: 20),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Oxford Literary Festival',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 16,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                Text(
                  '23 Mar - 31 Mar, 2024',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.body,
                    fontSize: 13,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildInfoBit(String label, String value) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFFF0F7FF),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            label,
            style: GoogleFonts.inter(
              color: GoOutsColors.onSurfaceVariant,
              fontSize: 12,
            ),
          ),
          const SizedBox(height: 4),
          Text(
            value,
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 15,
              fontWeight: FontWeight.w700,
              height: 1.2,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildDemandDetectionCard() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFFE0F7FF),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.trending_up, color: GoOutsColors.alertBg, size: 18),
              const SizedBox(width: 8),
              Text(
                'High Demand Detected',
                style: GoogleFonts.inter(
                  color: GoOutsColors.alertBg,
                  fontSize: 15,
                  fontWeight: FontWeight.w700,
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          RichText(
            text: TextSpan(
              style: GoogleFonts.inter(color: GoOutsColors.alertBg, fontSize: 14, height: 1.4),
              children: const [
                TextSpan(text: 'Comparable properties are asking '),
                TextSpan(text: '£210/night', style: TextStyle(fontWeight: FontWeight.w800)),
                TextSpan(text: ' this weekend.'),
              ],
            ),
          ),
          const SizedBox(height: 16),
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(8),
            ),
            child: Row(
              children: [
                const Icon(Icons.circle, color: GoOutsColors.primary, size: 8),
                const SizedBox(width: 8),
                Text(
                  'Recommended: Increase by 15%',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 13,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildNearbyActivitySection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16),
          child: Text(
            'Nearby Activity',
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 18,
              fontWeight: FontWeight.w700,
            ),
          ),
        ),
        const SizedBox(height: 12),
        Container(
          height: 200,
          margin: const EdgeInsets.symmetric(horizontal: 16),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(16),
            image: const DecorationImage(
              image: NetworkImage('https://images.unsplash.com/photo-1524813686514-a57563d77965?auto=format&fit=crop&q=80&w=800'),
              fit: BoxFit.cover,
              opacity: 0.8,
            ),
          ),
          child: Stack(
            children: [
              Center(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                      decoration: BoxDecoration(
                        color: GoOutsColors.alertBg,
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          const Icon(Icons.event, color: Colors.white, size: 14),
                          const SizedBox(width: 6),
                          Text(
                            'Event Venue',
                            style: GoogleFonts.inter(color: Colors.white, fontSize: 12, fontWeight: FontWeight.w700),
                          ),
                        ],
                      ),
                    ),
                    const Icon(Icons.arrow_drop_down, color: GoOutsColors.alertBg, size: 32),
                  ],
                ),
              ),
              const Positioned(
                bottom: 40,
                left: 80,
                child: Icon(Icons.home, color: GoOutsColors.alertBg, size: 32),
              ),
            ],
          ),
        ),
        const SizedBox(height: 24),
        _buildActionTile(Icons.calendar_month, 'View availability', 'Check for open nights during the festival'),
        _buildActionTile(Icons.trending_up, 'Seasonal analytics', 'See how your rates compared last year'),
        const SizedBox(height: 40),
      ],
    );
  }

  Widget _buildActionTile(IconData icon, String title, String subtitle) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: GoOutsColors.surface,
          borderRadius: BorderRadius.circular(12),
          boxShadow: [
            BoxShadow(color: Colors.black.withValues(alpha: 0.02), blurRadius: 4, offset: const Offset(0, 2)),
          ],
        ),
        child: Row(
          children: [
            Icon(icon, color: GoOutsColors.navy, size: 24),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    title,
                    style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 15, fontWeight: FontWeight.w700),
                  ),
                  Text(
                    subtitle,
                    style: GoogleFonts.inter(color: GoOutsColors.body, fontSize: 13),
                  ),
                ],
              ),
            ),
            const Icon(Icons.chevron_right, color: GoOutsColors.onSurfaceVariant),
          ],
        ),
      ),
    );
  }
}
