// Generated by Google Stitch. Source folder: 10-my_listings
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';

import 'host_bottom_nav.dart';


class MyListingsScreen extends StatelessWidget {
  const MyListingsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.navy),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'My listings',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.add, color: GoOutsColors.navy),
            onPressed: () {},
          ),
        ],
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            _buildPortfolioSummary(),
            _buildListingItem(
              title: 'Harbour Side Penthouse',
              imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=600',
              status: 'LIVE',
              occupancy: '84%',
              partnerCount: 12,
            ),
            _buildListingItem(
              title: 'Chelsea Mews Cottage',
              imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=600',
              status: 'PAUSED',
              occupancy: '0%',
              partnerCount: 8,
            ),
            _buildListingItem(
              title: 'The Shoreditch Loft',
              imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=600',
              status: 'DRAFT',
              occupancy: null,
              partnerCount: 24,
            ),
            _buildListingItem(
              title: 'Ocean View Villa',
              imageUrl: 'https://images.unsplash.com/photo-1580587767303-93630f9a7213?auto=format&fit=crop&q=80&w=600',
              status: 'LIVE',
              occupancy: '92%',
              partnerCount: 5,
            ),
            const SizedBox(height: 40),
          ],
        ),
      ),
      bottomNavigationBar: const HostBottomNav(current: HostTab.listings),
    );
  }

  Widget _buildPortfolioSummary() {
    return Container(
      padding: const EdgeInsets.all(20),
      color: GoOutsColors.surface,
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          _buildSummaryItem('Total Value', '£14,250'),
          _buildSummaryItem('Active', '8 Listings'),
          _buildSummaryItem('Avg Occ.', '78%'),
        ],
      ),
    );
  }

  Widget _buildSummaryItem(String label, String value) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: GoogleFonts.inter(
            color: GoOutsColors.onSurfaceVariant,
            fontSize: 13,
            fontWeight: FontWeight.w500,
          ),
        ),
        const SizedBox(height: 4),
        Text(
          value,
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 16,
            fontWeight: FontWeight.w700,
          ),
        ),
      ],
    );
  }

  Widget _buildListingItem({
    required String title,
    required String imageUrl,
    required String status,
    String? occupancy,
    required int partnerCount,
  }) {
    Color statusColor;
    switch (status) {
      case 'LIVE':
        statusColor = GoOutsColors.live;
        break;
      case 'PAUSED':
        statusColor = GoOutsColors.paused;
        break;
      default:
        statusColor = GoOutsColors.draft;
    }

    return Container(
      margin: const EdgeInsets.only(bottom: 24),
      decoration: const BoxDecoration(
        color: GoOutsColors.surface,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Stack(
            children: [
              Image.network(
                imageUrl,
                height: 220,
                width: double.infinity,
                fit: BoxFit.cover,
              ),
              Positioned(
                top: 16,
                left: 16,
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                  decoration: BoxDecoration(
                    color: statusColor.withValues(alpha: 0.9),
                    borderRadius: BorderRadius.circular(20),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      const Icon(Icons.circle, color: Colors.white, size: 6),
                      const SizedBox(width: 6),
                      Text(
                        status,
                        style: GoogleFonts.inter(
                          color: Colors.white,
                          fontSize: 10,
                          fontWeight: FontWeight.w800,
                          letterSpacing: 0.5,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              if (occupancy != null)
                Positioned(
                  bottom: 16,
                  right: 16,
                  child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                    decoration: BoxDecoration(
                      color: Colors.white.withValues(alpha: 0.9),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Text(
                      '$occupancy Occupancy',
                      style: GoogleFonts.inter(
                        color: GoOutsColors.navy,
                        fontSize: 11,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                  ),
                ),
              if (status == 'DRAFT')
                const Positioned.fill(
                  child: Center(
                    child: Icon(Icons.image_outlined, color: Colors.white, size: 32),
                  ),
                ),
            ],
          ),
          Padding(
            padding: const EdgeInsets.all(16),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  title,
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 16,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const Icon(Icons.more_vert, color: GoOutsColors.navy, size: 20),
              ],
            ),
          ),
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
            child: Row(
              children: [
                const Icon(Icons.explore_outlined, size: 14, color: GoOutsColors.body),
                const SizedBox(width: 8),
                Text(
                  '$partnerCount GoOuts partners nearby',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.body,
                    fontSize: 13,
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
