// Generated by Google Stitch. Source folder: 1-host_dashboard
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';


class HostDashboardScreen extends StatelessWidget {
  const HostDashboardScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        title: Text(
          'Dashboard',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
        leading: IconButton(
          // Was `leading: const Icon(...)` — a decorative arrow that
          // was NOT tappable. It looked like a back button and did
          // nothing, which is worse than having no arrow at all.
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        actions: const [
          Icon(Icons.notifications_none, color: GoOutsColors.navy),
          SizedBox(width: 16),
          CircleAvatar(
            radius: 16,
            backgroundImage: NetworkImage('https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=100'),
          ),
          SizedBox(width: 16),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Good morning, Sarah',
              style: GoogleFonts.inter(
                color: GoOutsColors.navy,
                fontSize: 24,
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'Here is an overview of your hosting operations.',
              style: GoogleFonts.inter(
                color: GoOutsColors.body,
                fontSize: 15,
              ),
            ),
            const SizedBox(height: 24),
            _buildSummaryGrid(),
            const SizedBox(height: 24),
            _buildActionRequired(),
            const SizedBox(height: 24),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  'Next Arrivals',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.primary,
                    fontSize: 15,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                Text(
                  'View all',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.primary,
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            _buildArrivalList(),
            const SizedBox(height: 40),
          ],
        ),
      ),
      bottomNavigationBar: _buildBottomNav(),
    );
  }

  Widget _buildSummaryGrid() {
    return Column(
      children: [
        Row(
          children: [
            Expanded(child: _buildStatCard('EARNINGS (OCT)', '£2,450', trend: '+12% vs last month')),
            const SizedBox(width: 8),
            Expanded(child: _buildStatCard('UPCOMING STAYS', '12', subValue: 'Next 30 days')),
          ],
        ),
        const SizedBox(height: 8),
        _buildStatCard(
          'AVG RATING', 
          '4.9 / 5.0', 
          icon: Icons.star_border,
          ratingStars: 5,
        ),
      ],
    );
  }

  Widget _buildStatCard(String label, String value, {String? trend, String? subValue, IconData? icon, int? ratingStars}) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                label,
                style: GoogleFonts.inter(
                  color: GoOutsColors.body.withValues(alpha: 0.6),
                  fontSize: 12,
                  fontWeight: FontWeight.w600,
                  letterSpacing: 0.5,
                ),
              ),
              if (icon != null) Icon(icon, color: GoOutsColors.primary, size: 18),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            value,
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 24,
              fontWeight: FontWeight.w700,
            ),
          ),
          if (trend != null) ...[
            const SizedBox(height: 4),
            Row(
              children: [
                const Icon(Icons.trending_up, color: GoOutsColors.primary, size: 14),
                const SizedBox(width: 4),
                Text(
                  trend,
                  style: GoogleFonts.inter(
                    color: GoOutsColors.primary,
                    fontSize: 12,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ],
            ),
          ],
          if (subValue != null) ...[
            const SizedBox(height: 4),
            Text(
              subValue,
              style: GoogleFonts.inter(
                color: GoOutsColors.body,
                fontSize: 12,
              ),
            ),
          ],
          if (ratingStars != null) ...[
            const SizedBox(height: 8),
            Row(
              children: List.generate(5, (index) => const Icon(Icons.star, color: GoOutsColors.primary, size: 16)),
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildActionRequired() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Action Required',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 18,
            fontWeight: FontWeight.w700,
          ),
        ),
        const SizedBox(height: 12),
        Container(
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            color: GoOutsColors.tint.withValues(alpha: 0.5),
            borderRadius: BorderRadius.circular(16),
            border: Border.all(color: GoOutsColors.primary.withValues(alpha: 0.1)),
          ),
          child: Column(
            children: [
              Row(
                children: [
                  const CircleAvatar(
                    radius: 24,
                    backgroundImage: NetworkImage('https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200'),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            Text(
                              'Sarah Jenkins',
                              style: GoogleFonts.inter(
                                color: GoOutsColors.navy,
                                fontSize: 16,
                                fontWeight: FontWeight.w700,
                              ),
                            ),
                            const SizedBox(width: 8),
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                              decoration: BoxDecoration(
                                color: GoOutsColors.surface,
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(color: GoOutsColors.primary.withValues(alpha: 0.2)),
                              ),
                              child: Text(
                                'New Guest',
                                style: GoogleFonts.inter(
                                  color: GoOutsColors.primary,
                                  fontSize: 10,
                                  fontWeight: FontWeight.w700,
                                ),
                              ),
                            ),
                          ],
                        ),
                        Text(
                          'Requested to book The Seaside Cottage',
                          style: GoogleFonts.inter(
                            color: GoOutsColors.navy,
                            fontSize: 14,
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                        const SizedBox(height: 4),
                        Text(
                          '12 - 15 Nov • 2 Guests',
                          style: GoogleFonts.inter(
                            color: GoOutsColors.body,
                            fontSize: 13,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 20),
              Row(
                children: [
                  Expanded(
                    child: OutlinedButton(
                      onPressed: () {},
                      style: OutlinedButton.styleFrom(
                        backgroundColor: GoOutsColors.surface,
                        side: BorderSide.none,
                        minimumSize: const Size(0, 48),
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                      ),
                      child: Text(
                        'Decline',
                        style: GoogleFonts.inter(
                          color: GoOutsColors.navy,
                          fontSize: 16,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: ElevatedButton(
                      onPressed: () {},
                      style: ElevatedButton.styleFrom(
                        backgroundColor: GoOutsColors.primary,
                        minimumSize: const Size(0, 48),
                        elevation: 0,
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                      ),
                      child: Text(
                        'Accept',
                        style: GoogleFonts.inter(
                          color: Colors.white,
                          fontSize: 16,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildArrivalList() {
    final arrivals = [
      {'name': 'James Smith', 'status': 'Confirmed', 'dates': 'Today • 2 Nights', 'initials': 'JS'},
      {'name': 'Elena Rossi', 'status': 'Confirmed', 'dates': 'Tomorrow • 5 Nights', 'image': 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=150'},
      {'name': 'Michael Chen', 'status': 'Confirmed', 'dates': '28 Oct • 1 Night', 'initials': 'MC'},
    ];

    return Container(
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        children: arrivals.asMap().entries.map((entry) {
          final isLast = entry.key == arrivals.length - 1;
          final arrival = entry.value;
          return Column(
            children: [
              ListTile(
                contentPadding: const EdgeInsets.all(16),
                leading: arrival.containsKey('image') 
                  ? CircleAvatar(backgroundImage: NetworkImage(arrival['image']!))
                  : CircleAvatar(
                      backgroundColor: GoOutsColors.tint,
                      child: Text(
                        arrival['initials']!,
                        style: GoogleFonts.inter(color: GoOutsColors.primary, fontWeight: FontWeight.w700),
                      ),
                    ),
                title: Text(
                  arrival['name']!,
                  style: GoogleFonts.inter(color: GoOutsColors.navy, fontWeight: FontWeight.w700),
                ),
                subtitle: Text(
                  arrival['dates']!,
                  style: GoogleFonts.inter(color: GoOutsColors.body, fontSize: 13),
                ),
                trailing: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                  decoration: BoxDecoration(
                    color: GoOutsColors.tint,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      const Icon(Icons.check_circle_outline, color: GoOutsColors.primary, size: 14),
                      const SizedBox(width: 4),
                      Text(
                        arrival['status']!,
                        style: GoogleFonts.inter(
                          color: GoOutsColors.primary,
                          fontSize: 11,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              if (!isLast) const Divider(height: 1, color: GoOutsColors.background),
            ],
          );
        }).toList(),
      ),
    );
  }

  Widget _buildBottomNav() {
    return Container(
      decoration: const BoxDecoration(
        color: GoOutsColors.surface,
        border: Border(top: BorderSide(color: GoOutsColors.background, width: 1)),
      ),
      child: BottomNavigationBar(
        elevation: 0,
        backgroundColor: GoOutsColors.surface,
        selectedItemColor: GoOutsColors.primary,
        unselectedItemColor: GoOutsColors.body,
        type: BottomNavigationBarType.fixed,
        currentIndex: 0,
        selectedLabelStyle: GoogleFonts.inter(fontWeight: FontWeight.w700, fontSize: 11),
        unselectedLabelStyle: GoogleFonts.inter(fontWeight: FontWeight.w500, fontSize: 11),
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.dashboard_outlined), label: 'Dashboard'),
          BottomNavigationBarItem(icon: Icon(Icons.calendar_today_outlined), label: 'Bookings'),
          BottomNavigationBarItem(icon: Icon(Icons.holiday_village_outlined), label: 'Listings'),
          BottomNavigationBarItem(icon: Icon(Icons.mail_outline), label: 'Inbox'),
          BottomNavigationBarItem(icon: Icon(Icons.person_outline), label: 'Profile'),
        ],
      ),
    );
  }
}
