// Generated by Google Stitch. Source folder: 18-claim_status
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';

import 'host_bottom_nav.dart';


class ClaimStatusScreen extends StatelessWidget {
  const ClaimStatusScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.navy),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Claim Status',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Case ID: #12345',
              style: GoogleFonts.inter(
                color: GoOutsColors.primary,
                fontSize: 14,
                fontWeight: FontWeight.w600,
              ),
            ),
            const SizedBox(height: 4),
            Text(
              'Tracking your claim',
              style: GoogleFonts.inter(
                color: GoOutsColors.navy,
                fontSize: 24,
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 24),
            _buildTimelineAlert(),
            const SizedBox(height: 24),
            _buildItemSummary(),
            const SizedBox(height: 24),
            _buildProgressTimeline(),
            const SizedBox(height: 24),
            _buildDecisionDetails(),
            const SizedBox(height: 24),
            _buildSupportButton(),
            const SizedBox(height: 40),
          ],
        ),
      ),
      bottomNavigationBar: const HostBottomNav(current: HostTab.bookings),
    );
  }

  Widget _buildTimelineAlert() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: GoOutsColors.primary,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.info_outline, color: Colors.white, size: 24),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Decision Timeline',
                  style: GoogleFonts.inter(
                    color: Colors.white,
                    fontSize: 16,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'We aim to decide within five working days of receiving all guest documentation.',
                  style: GoogleFonts.inter(
                    color: Colors.white.withValues(alpha: 0.9),
                    fontSize: 14,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildItemSummary() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.02),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Item Summary',
                style: GoogleFonts.inter(
                  color: GoOutsColors.navy,
                  fontSize: 16,
                  fontWeight: FontWeight.w700,
                ),
              ),
              Text(
                '£240.00',
                style: GoogleFonts.inter(
                  color: GoOutsColors.primary,
                  fontSize: 18,
                  fontWeight: FontWeight.w700,
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: GoOutsColors.background,
              borderRadius: BorderRadius.circular(12),
            ),
            child: Row(
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(8),
                  child: Image.network(
                    'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&q=80&w=100',
                    width: 60,
                    height: 60,
                    fit: BoxFit.cover,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Living Room Carpet',
                        style: GoogleFonts.inter(
                          color: GoOutsColors.navy,
                          fontSize: 15,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      const SizedBox(height: 2),
                      Text(
                        'Reported damage: Liquid stain',
                        style: GoogleFonts.inter(
                          color: GoOutsColors.onSurfaceVariant,
                          fontSize: 13,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildProgressTimeline() {
    final steps = [
      {'title': 'Submitted', 'subtitle': 'Claim created with evidence.', 'date': '16 Oct', 'isCompleted': true},
      {'title': 'Guest notified', 'subtitle': 'Email and app notification sent.', 'date': '17 Oct', 'isCompleted': true},
      {'title': 'Guest responded', 'subtitle': 'Response and counter-evidence received.', 'date': '18 Oct', 'isCompleted': true},
      {'title': 'Under review', 'subtitle': 'An agent is currently assessing the case details.', 'date': '', 'isCurrent': true},
      {'title': 'Decided', 'subtitle': 'Final outcome and payout details.', 'date': '', 'isFuture': true},
    ];

    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Progress Timeline',
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 16,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 24),
          ListView.builder(
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            itemCount: steps.length,
            itemBuilder: (context, index) {
              final step = steps[index];
              final isLast = index == steps.length - 1;
              return IntrinsicHeight(
                child: Row(
                  children: [
                    Column(
                      children: [
                        _buildTimelineIndicator(
                          step['isCompleted'] == true,
                          step['isCurrent'] == true,
                          step['isFuture'] == true,
                        ),
                        if (!isLast)
                          Expanded(
                            child: Container(
                              width: 2,
                              color: GoOutsColors.border,
                            ),
                          ),
                      ],
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: Padding(
                        padding: const EdgeInsets.only(bottom: 24),
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    step['title'] as String,
                                    style: GoogleFonts.inter(
                                      color: GoOutsColors.navy,
                                      fontSize: 15,
                                      fontWeight: FontWeight.w700,
                                    ),
                                  ),
                                  const SizedBox(height: 4),
                                  Text(
                                    step['subtitle'] as String,
                                    style: GoogleFonts.inter(
                                      color: GoOutsColors.body,
                                      fontSize: 13,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            if (step['date'] != '')
                              Text(
                                step['date'] as String,
                                style: GoogleFonts.inter(
                                  color: GoOutsColors.onSurfaceVariant,
                                  fontSize: 12,
                                  fontWeight: FontWeight.w500,
                                ),
                              ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildTimelineIndicator(bool completed, bool current, bool future) {
    if (completed) {
      return Container(
        width: 24,
        height: 24,
        decoration: const BoxDecoration(color: GoOutsColors.primary, shape: BoxShape.circle),
        child: const Icon(Icons.check, color: Colors.white, size: 16),
      );
    } else if (current) {
      return Container(
        width: 24,
        height: 24,
        decoration: BoxDecoration(
          border: Border.all(color: GoOutsColors.primary, width: 2),
          shape: BoxShape.circle,
        ),
        child: Center(
          child: Container(
            width: 8,
            height: 8,
            decoration: const BoxDecoration(color: GoOutsColors.primary, shape: BoxShape.circle),
          ),
        ),
      );
    } else {
      return Container(
        width: 24,
        height: 24,
        decoration: BoxDecoration(
          border: Border.all(color: GoOutsColors.border, width: 2),
          shape: BoxShape.circle,
        ),
      );
    }
  }

  Widget _buildDecisionDetails() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: GoOutsColors.border.withValues(alpha: 0.5)),
      ),
      child: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Decision Details',
                style: GoogleFonts.inter(
                  color: GoOutsColors.navy,
                  fontSize: 16,
                  fontWeight: FontWeight.w700,
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                decoration: BoxDecoration(
                  color: GoOutsColors.primary.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Text(
                  'In progress',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.primary,
                    fontSize: 12,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 32),
          Icon(Icons.assignment_outlined, color: GoOutsColors.onSurfaceVariant.withValues(alpha: 0.3), size: 48),
          const SizedBox(height: 16),
          Text(
            'Reasoning and weight of evidence will appear here once a resolution has been reached.',
            textAlign: TextAlign.center,
            style: GoogleFonts.inter(
              color: GoOutsColors.body,
              fontSize: 14,
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSupportButton() {
    return ElevatedButton.icon(
      onPressed: () {},
      icon: const Icon(Icons.chat_bubble_outline, color: GoOutsColors.primary, size: 20),
      label: Text(
        'Contact Support',
        style: GoogleFonts.inter(
          color: GoOutsColors.primary,
          fontSize: 16,
          fontWeight: FontWeight.w600,
        ),
      ),
      style: ElevatedButton.styleFrom(
        backgroundColor: const Color(0xFFE0F3FB),
        minimumSize: const Size(double.infinity, 56),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        elevation: 0,
      ),
    );
  }
}
