// Generated by Google Stitch. Source folder: 23-notification_settings
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';


class NotificationSettingsScreen extends StatefulWidget {
  const NotificationSettingsScreen({super.key});

  @override
  State<NotificationSettingsScreen> createState() => _NotificationSettingsScreenState();
}

class _NotificationSettingsScreenState extends State<NotificationSettingsScreen> {
  // Mock state for switches
  final Map<String, bool> _settings = {
    'new_requests_push': true,
    'new_requests_email': true,
    'confirmations_push': true,
    'confirmations_email': false,
    'cancellations_push': true,
    'cancellations_email': true,
    'pricing_push': false,
    'pricing_email': true,
    'maintenance_push': true,
    'maintenance_email': true,
    'status_push': true,
    'status_email': true,
    'compliance_push': true,
    'compliance_email': true,
  };

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Notifications',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
        actions: const [
          Padding(
            padding: EdgeInsets.only(right: 16.0),
            child: CircleAvatar(
              radius: 18,
              backgroundImage: NetworkImage('https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=100'),
            ),
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Alert Preferences',
              style: GoogleFonts.inter(
                color: GoOutsColors.navy,
                fontSize: 18,
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'Choose how you\'d like to be notified about your properties and bookings.',
              style: GoogleFonts.inter(
                color: GoOutsColors.body,
                fontSize: 14,
                height: 1.5,
              ),
            ),
            const SizedBox(height: 24),
            _buildSection(
              title: 'Booking Updates',
              icon: Icons.calendar_today_outlined,
              items: [
                _buildSettingRow(
                  'New requests',
                  'Instant alerts for new booking inquiries',
                  'new_requests',
                ),
                _buildSettingRow(
                  'Confirmations',
                  'When a booking is finalized',
                  'confirmations',
                ),
                _buildSettingRow(
                  'Cancellations',
                  'Urgent alerts for cancelled stays',
                  'cancellations',
                ),
              ],
            ),
            const SizedBox(height: 20),
            _buildSection(
              title: 'Property Alerts',
              icon: Icons.home_work_outlined,
              items: [
                _buildSettingRow(
                  'Pricing alerts',
                  'Market trend and dynamic price updates',
                  'pricing',
                ),
                _buildSettingRow(
                  'Maintenance',
                  'Scheduled inspections and repair alerts',
                  'maintenance',
                ),
              ],
            ),
            const SizedBox(height: 20),
            _buildSection(
              title: 'Claims & Legal',
              icon: Icons.gavel_outlined,
              items: [
                _buildSettingRow(
                  'Status updates',
                  'Progress reports on active insurance claims',
                  'status',
                ),
                _buildSettingRow(
                  'Compliance',
                  'Important regulatory and policy changes',
                  'compliance',
                ),
              ],
            ),
            const SizedBox(height: 32),
            ElevatedButton(
              onPressed: () {},
              style: ElevatedButton.styleFrom(
                backgroundColor: GoOutsColors.primary,
                minimumSize: const Size(double.infinity, 56),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                elevation: 0,
              ),
              child: Text(
                'Save Changes',
                style: GoogleFonts.inter(
                  color: Colors.white,
                  fontSize: 16,
                  fontWeight: FontWeight.w700,
                ),
              ),
            ),
            const SizedBox(height: 40),
          ],
        ),
      ),
      bottomNavigationBar: _buildBottomNav(),
    );
  }

  Widget _buildSection({
    required String title,
    required IconData icon,
    required List<Widget> items,
  }) {
    return Container(
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.03),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Row(
              children: [
                Icon(icon, color: GoOutsColors.primary, size: 20),
                const SizedBox(width: 12),
                Text(
                  title,
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 16,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ],
            ),
          ),
          const Divider(height: 1, color: Color(0xFFF1F5F9)),
          ...items,
        ],
      ),
    );
  }

  Widget _buildSettingRow(String title, String subtitle, String key) {
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      title,
                      style: GoogleFonts.inter(
                        color: GoOutsColors.navy,
                        fontSize: 15,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      subtitle,
                      style: GoogleFonts.inter(
                        color: GoOutsColors.onSurfaceVariant,
                        fontSize: 13,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 16),
              _buildTogglePair(key),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildTogglePair(String key) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        _buildSwitchColumn('PUSH', '${key}_push'),
        const SizedBox(width: 16),
        _buildSwitchColumn('EMAIL', '${key}_email'),
      ],
    );
  }

  Widget _buildSwitchColumn(String label, String stateKey) {
    return Column(
      children: [
        Text(
          label,
          style: GoogleFonts.inter(
            color: GoOutsColors.onSurfaceVariant,
            fontSize: 10,
            fontWeight: FontWeight.w700,
            letterSpacing: 0.5,
          ),
        ),
        const SizedBox(height: 4),
        Transform.scale(
          scale: 0.8,
          child: Switch(
            value: _settings[stateKey] ?? false,
            onChanged: (val) {
              setState(() => _settings[stateKey] = val);
            },
            activeThumbColor: Colors.white,
            activeTrackColor: GoOutsColors.primary,
            inactiveThumbColor: Colors.white,
            inactiveTrackColor: const Color(0xFFE2E8F0),
          ),
        ),
      ],
    );
  }

  Widget _buildBottomNav() {
    return Container(
      decoration: const BoxDecoration(
        color: GoOutsColors.surface,
        border: Border(top: BorderSide(color: Color(0xFFEDF2F7), width: 1)),
      ),
      child: BottomNavigationBar(
        elevation: 0,
        backgroundColor: GoOutsColors.surface,
        selectedItemColor: GoOutsColors.primary,
        unselectedItemColor: GoOutsColors.onSurfaceVariant,
        type: BottomNavigationBarType.fixed,
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.home_outlined), label: 'Home'),
          BottomNavigationBarItem(icon: Icon(Icons.calendar_month_outlined), label: 'Bookings'),
          BottomNavigationBarItem(icon: Icon(Icons.payments_outlined), label: 'Earnings'),
          BottomNavigationBarItem(icon: Icon(Icons.menu), label: 'Menu'),
        ],
      ),
    );
  }
}
