// Generated by Google Stitch. Source folder: 12-availability_calendar
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';

import 'host_bottom_nav.dart';


class AvailabilityCalendarScreen extends StatelessWidget {
  const AvailabilityCalendarScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.navy),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Calendar',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.tune, color: GoOutsColors.navy),
            onPressed: () {},
          ),
          IconButton(
            icon: const Icon(Icons.search, color: GoOutsColors.navy),
            onPressed: () {},
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildPropertySelector(),
                  const SizedBox(height: 24),
                  _buildCalendarHeader(),
                  const SizedBox(height: 16),
                  _buildCalendarGrid(),
                  const SizedBox(height: 16),
                  _buildLegend(),
                  const SizedBox(height: 24),
                  _buildMetricsRow(),
                  const SizedBox(height: 16),
                  _buildPricingSuggestion(),
                ],
              ),
            ),
          ),
          _buildManageAvailabilitySheet(),
        ],
      ),
      bottomNavigationBar: const HostBottomNav(current: HostTab.bookings),
    );
  }

  Widget _buildPropertySelector() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.02),
            blurRadius: 8,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Selected Property',
                style: GoogleFonts.inter(
                  color: GoOutsColors.onSurfaceVariant,
                  fontSize: 12,
                ),
              ),
              const SizedBox(height: 2),
              Text(
                'The Coastal Loft, St Ives',
                style: GoogleFonts.inter(
                  color: const Color(0xFF00668C),
                  fontSize: 15,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ],
          ),
          const Icon(Icons.keyboard_arrow_down, color: GoOutsColors.onSurfaceVariant),
        ],
      ),
    );
  }

  Widget _buildCalendarHeader() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          'September 2024',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 18,
            fontWeight: FontWeight.w700,
          ),
        ),
        Row(
          children: [
            IconButton(
              icon: const Icon(Icons.chevron_left, color: GoOutsColors.navy),
              onPressed: () {},
            ),
            IconButton(
              icon: const Icon(Icons.chevron_right, color: GoOutsColors.navy),
              onPressed: () {},
            ),
          ],
        ),
      ],
    );
  }

  Widget _buildCalendarGrid() {
    final days = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'];
    return Container(
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.02),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        children: [
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 16),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: days.map((day) => Text(
                day,
                style: GoogleFonts.inter(
                  color: GoOutsColors.onSurfaceVariant,
                  fontSize: 11,
                  fontWeight: FontWeight.w500,
                ),
              )).toList(),
            ),
          ),
          const Divider(height: 1, color: Color(0xFFF1F5F9)),
          _buildCalendarRow(['26', '27', '28', '29', '30', '31', '1'], isOtherMonth: true, price: '£145'),
          _buildCalendarRow(['2', '3', '4', '5', '6', '7', '8'], status: ['Booked', 'Booked', 'Booked', '£145', '£160', 'Maintenance', '£160']),
          _buildCalendarRow(['9', '10', '11', '12', '13', '14', '15'], status: ['£145', 'Booked', '£145', '£145', '£180', '£180', '£160']),
          _buildCalendarRow(['16', '17', '18', '19', '20', '21', ''], status: ['Booked', 'Booked', 'Blocked', '£145', '£185', '£185', '']),
        ],
      ),
    );
  }

  Widget _buildCalendarRow(List<String> dates, {bool isOtherMonth = false, String? price, List<String>? status}) {
    return IntrinsicHeight(
      child: Row(
        children: List.generate(7, (index) {
          final date = dates[index];
          final currentStatus = status?[index] ?? '';
          
          Color? bgColor;
          if (currentStatus == 'Booked') bgColor = const Color(0xFF005F84);
          if (currentStatus == 'Blocked') bgColor = const Color(0xFFDCEBFF);
          if (currentStatus == 'Maintenance') bgColor = const Color(0xFFF8F9FF);

          return Expanded(
            child: Container(
              height: 70,
              decoration: BoxDecoration(
                color: bgColor,
                border: Border.all(color: const Color(0xFFF1F5F9), width: 0.5),
              ),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Padding(
                    padding: const EdgeInsets.all(4.0),
                    child: Align(
                      alignment: Alignment.topLeft,
                      child: Text(
                        date,
                        style: GoogleFonts.inter(
                          color: isOtherMonth ? GoOutsColors.onSurfaceVariant.withValues(alpha: 0.5) : GoOutsColors.navy,
                          fontSize: 13,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  ),
                  if (currentStatus.isNotEmpty)
                    Padding(
                      padding: const EdgeInsets.only(bottom: 8.0),
                      child: Text(
                        currentStatus,
                        style: GoogleFonts.inter(
                          color: currentStatus == 'Booked' ? Colors.white : (currentStatus == 'Blocked' ? const Color(0xFF005F84) : GoOutsColors.onSurfaceVariant),
                          fontSize: 9,
                          fontWeight: currentStatus == 'Booked' ? FontWeight.w500 : FontWeight.w400,
                        ),
                      ),
                    ),
                  if (price != null && index == 6)
                     Padding(
                      padding: const EdgeInsets.only(bottom: 8.0),
                      child: Text(
                        price,
                        style: GoogleFonts.inter(
                          color: GoOutsColors.onSurfaceVariant,
                          fontSize: 9,
                        ),
                      ),
                    ),
                ],
              ),
            ),
          );
        }),
      ),
    );
  }

  Widget _buildLegend() {
    return Row(
      children: [
        _buildLegendItem('Booked', const Color(0xFF005F84)),
        const SizedBox(width: 16),
        _buildLegendItem('Blocked', const Color(0xFFDCEBFF)),
        const SizedBox(width: 16),
        _buildLegendItem('Available', Colors.white, border: true),
      ],
    );
  }

  Widget _buildLegendItem(String label, Color color, {bool border = false}) {
    return Row(
      children: [
        Container(
          width: 16,
          height: 16,
          decoration: BoxDecoration(
            color: color,
            borderRadius: BorderRadius.circular(4),
            border: border ? Border.all(color: GoOutsColors.border) : null,
          ),
        ),
        const SizedBox(width: 8),
        Text(
          label,
          style: GoogleFonts.inter(
            color: GoOutsColors.body,
            fontSize: 13,
            fontWeight: FontWeight.w500,
          ),
        ),
      ],
    );
  }

  Widget _buildMetricsRow() {
    return Row(
      children: [
        Expanded(
          child: _buildMetricCard('Occupancy', '68%', const Color(0xFFA5E1F9)),
        ),
        const SizedBox(width: 16),
        Expanded(
          child: _buildMetricCard('Revenue Est.', '£2,450', GoOutsColors.primary),
        ),
      ],
    );
  }

  Widget _buildMetricCard(String label, String value, Color color) {
    bool isPrimary = color == GoOutsColors.primary;
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: color,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            label,
            style: GoogleFonts.inter(
              color: isPrimary ? Colors.white.withValues(alpha: 0.9) : GoOutsColors.navy.withValues(alpha: 0.7),
              fontSize: 13,
            ),
          ),
          const SizedBox(height: 4),
          Text(
            value,
            style: GoogleFonts.inter(
              color: isPrimary ? Colors.white : GoOutsColors.navy,
              fontSize: 22,
              fontWeight: FontWeight.w700,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPricingSuggestion() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFF6B728E), // Slate/Blue-grey from screenshot
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.lightbulb_outline, color: Colors.white, size: 20),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              'Consider lowering prices for 5-9 Sep to attract last-minute bookings. Market demand is lower than average.',
              style: GoogleFonts.inter(
                color: Colors.white,
                fontSize: 13,
                height: 1.4,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildManageAvailabilitySheet() {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: const BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.vertical(top: Radius.circular(32)),
        boxShadow: [
          BoxShadow(color: Colors.black12, blurRadius: 20, offset: Offset(0, -5)),
        ],
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Center(
            child: Container(
              width: 48,
              height: 4,
              decoration: BoxDecoration(
                color: const Color(0xFFE2E8F0),
                borderRadius: BorderRadius.circular(2),
              ),
            ),
          ),
          const SizedBox(height: 24),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'September 12, 2024',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 22,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  Text(
                    'Manage availability and pricing',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.onSurfaceVariant,
                      fontSize: 14,
                    ),
                  ),
                ],
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                decoration: BoxDecoration(
                  color: const Color(0xFFF1F5F9),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Text(
                  'Available',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 12,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 24),
          Text(
            'Nightly Rate',
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 14,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 8),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            decoration: BoxDecoration(
              color: const Color(0xFFF8FAFC),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: GoOutsColors.border),
            ),
            child: TextField(
              decoration: InputDecoration(
                icon: Text('£', style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 16, fontWeight: FontWeight.w600)),
                hintText: '145',
                border: InputBorder.none,
              ),
            ),
          ),
          const SizedBox(height: 24),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: const Color(0xFFF8FAFC),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Property Available',
                        style: GoogleFonts.inter(
                          color: GoOutsColors.navy,
                          fontSize: 15,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      Text(
                        'Accept new bookings for this date',
                        style: GoogleFonts.inter(
                          color: GoOutsColors.onSurfaceVariant,
                          fontSize: 12,
                        ),
                      ),
                    ],
                  ),
                ),
                Switch(
                  value: true,
                  onChanged: (val) {},
                  activeThumbColor: Colors.white,
                  activeTrackColor: const Color(0xFF00668C),
                ),
              ],
            ),
          ),
          const SizedBox(height: 24),
          Text(
            'Block Out Reason (Internal)',
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 14,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 8),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            decoration: BoxDecoration(
              color: const Color(0xFFF8FAFC),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: GoOutsColors.border),
            ),
            child: TextField(
              decoration: InputDecoration(
                hintText: 'e.g. Personal use, Painting',
                hintStyle: GoogleFonts.inter(color: GoOutsColors.onSurfaceVariant.withValues(alpha: 0.5)),
                border: InputBorder.none,
              ),
            ),
          ),
          const SizedBox(height: 32),
          Row(
            children: [
              Expanded(
                child: TextButton(
                  onPressed: () {},
                  style: TextButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    backgroundColor: const Color(0xFFE2E8F0),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                  child: Text('Cancel', style: GoogleFonts.inter(color: const Color(0xFF005F84), fontWeight: FontWeight.w600)),
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: ElevatedButton(
                  onPressed: () {},
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF005F84),
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    elevation: 0,
                  ),
                  child: Text('Save Changes', style: GoogleFonts.inter(color: Colors.white, fontWeight: FontWeight.w600)),
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
        ],
      ),
    );
  }
}
