// Generated by Google Stitch. Source folder: 20-host_earnings
//
// ── ⚠ GUARDED 9 August 2026, BEFORE BUILD 9. READ THIS. ────────────────────
//
// This screen used to render Stitch's invented figures to real hosts:
//
//     £14,840 total earnings · £3,200 gross · "Commission (15%)"
//     £2,720 net · a payout history dated 2023 with "Bank Transfer" and
//     "GoOuts Credit" methods · stock Unsplash property photographs
//
// Every one of those numbers was fictional, and the screen is a PERMANENT
// BOTTOM-NAV TAB — one of five, reachable from every other screen in the app.
// It was missed by the earlier wiring passes because nothing pushed to it
// until host_bottom_nav made it a tab.
//
// Two things made this worse than ordinary placeholder copy:
//
//   1. It stated money had ALREADY BEEN PAID, by bank transfer, on specific
//      dates. No payment provider is integrated. Nothing has ever been paid
//      to anyone. This is precisely the driver Instant Pay mistake — a button
//      that told drivers their wages had reached their bank — which this
//      codebase has a written rule against repeating.
//
//   2. "Commission (15%)" contradicts the platform. stay_config.js sets
//      hostCommissionPct to 12.0. A host reading 15% here and 12% in their
//      booking details has been given two different answers about what GoOuts
//      takes from them.
//
// The old body is deleted rather than commented out. Commented-out fake money
// is one uncomment away from shipping again.
//
// WHEN EARNINGS IS BUILT: read from /stay_bookings filtered by hostUid with
// status confirmed and the payout fields from stay_config.js
// (payoutReleaseHoursAfterCheckIn, newHostPayoutHoldDays). Show pricing
// .hostPayout, never pricing.total — see host_15_booking_details_screen.dart
// for why. Delete this guard then, not before.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';

import 'host_bottom_nav.dart';
import 'host_routes.dart';


class HostEarningsScreen extends StatelessWidget {
  const HostEarningsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Earnings',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            const SizedBox(height: 24),
            Center(
              child: Container(
                width: 72,
                height: 72,
                decoration: BoxDecoration(
                  color: GoOutsColors.tint,
                  shape: BoxShape.circle,
                ),
                child: const Icon(Icons.payments_outlined,
                    size: 34, color: GoOutsColors.primary),
              ),
            ),
            const SizedBox(height: 24),
            Text(
              'Earnings open when payments go live',
              textAlign: TextAlign.left,
              style: GoogleFonts.inter(
                color: GoOutsColors.navy,
                fontSize: 20,
                fontWeight: FontWeight.w800,
                height: 1.3,
              ),
            ),
            const SizedBox(height: 12),
            Text(
              'GoOuts is not yet connected to a payment provider, so no money '
              'has been charged to guests and none has been paid out. Rather '
              'than show you a balance that is not real, this screen stays '
              'empty until it can tell you the truth.',
              style: GoogleFonts.inter(
                color: GoOutsColors.body,
                fontSize: 14,
                height: 1.55,
              ),
            ),
            const SizedBox(height: 24),
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: GoOutsColors.surface,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: GoOutsColors.border),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Text(
                    'What is already working',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 14.5,
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                  const SizedBox(height: 10),
                  _point('Your bookings are real and are being recorded.'),
                  _point('Each booking shows what you would receive, after '
                      'GoOuts commission.'),
                  _point('Your calendar, listings and guest requests all '
                      'work normally.'),
                ],
              ),
            ),
            const SizedBox(height: 20),
            OutlinedButton.icon(
              onPressed: () =>
                  Navigator.of(context).pushNamed(HostRoutes.requests),
              icon: const Icon(Icons.calendar_month_outlined, size: 18),
              label: const Text('See your bookings'),
              style: OutlinedButton.styleFrom(
                minimumSize: const Size(double.infinity, 50),
                foregroundColor: GoOutsColors.primary,
                side: const BorderSide(color: GoOutsColors.primary),
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12)),
              ),
            ),
            const SizedBox(height: 32),
          ],
        ),
      ),
      bottomNavigationBar: const HostBottomNav(current: HostTab.earnings),
    );
  }

  static Widget _point(String text) => Padding(
        padding: const EdgeInsets.only(bottom: 8),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            const Padding(
              padding: EdgeInsets.only(top: 3),
              child: Icon(Icons.check_rounded,
                  size: 15, color: GoOutsColors.success),
            ),
            const SizedBox(width: 10),
            Expanded(
              child: Text(
                text,
                style: GoogleFonts.inter(
                    fontSize: 13.5, color: GoOutsColors.body, height: 1.5),
              ),
            ),
          ],
        ),
      );

  // ── EVERYTHING BELOW WAS DELETED ────────────────────────────────────────
  //
  // _buildEarningsOverview, _buildPayoutBreakdown, _buildPayoutMethods,
  // _buildConfirmButton, _buildRecentPayoutsHeader, _buildRecentPayoutsList
  // and their helpers rendered the fictional figures described at the top of
  // this file. They are gone, not commented out.
}
