// Generated by Google Stitch. Source folder: 7-pricing_rules
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import 'host_routes.dart';

import '../../../theme/goouts_colors.dart';


class PricingAndRulesScreen extends StatefulWidget {
  const PricingAndRulesScreen({super.key});

  @override
  State<PricingAndRulesScreen> createState() => _PricingAndRulesScreenState();
}

class _PricingAndRulesScreenState extends State<PricingAndRulesScreen> {
  String _bookingMode = 'Accept automatically';
  String _selectedPolicy = 'Flexible';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          // Was `leading: const Icon(...)` — a decorative arrow that
          // was NOT tappable. It looked like a back button and did
          // nothing, which is worse than having no arrow at all.
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Create Listing',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
        actions: [
          TextButton(
            onPressed: () {},
            child: Text(
              'Save & Exit',
              style: GoogleFonts.inter(
                color: GoOutsColors.primary,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          const SizedBox(width: 8),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Pricing',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 18,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Set your base nightly rate and any additional fees.',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.body,
                      fontSize: 15,
                    ),
                  ),
                  const SizedBox(height: 24),
                  _buildPricingCard(),
                  const SizedBox(height: 32),
                  Text(
                    'Booking mode',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 18,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Choose how you want to handle incoming booking requests.',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.body,
                      fontSize: 15,
                    ),
                  ),
                  const SizedBox(height: 16),
                  _buildBookingModeToggle(),
                  const SizedBox(height: 32),
                  Text(
                    'Cancellation policy',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 18,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Select a policy that provides transparency for your guests.',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.body,
                      fontSize: 15,
                    ),
                  ),
                  const SizedBox(height: 16),
                  _buildPolicyList(),
                  const SizedBox(height: 40),
                ],
              ),
            ),
          ),
          _buildFooter(),
        ],
      ),
    );
  }

  Widget _buildPricingCard() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildInputField('Nightly rate (£)', '0'),
          const SizedBox(height: 20),
          _buildInputField('Cleaning fee (£)', '0'),
        ],
      ),
    );
  }

  Widget _buildInputField(String label, String hint) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 15,
            fontWeight: FontWeight.w700,
          ),
        ),
        const SizedBox(height: 12),
        TextField(
          keyboardType: TextInputType.number,
          decoration: InputDecoration(
            hintText: '£  $hint',
            hintStyle: GoogleFonts.inter(color: GoOutsColors.body.withValues(alpha: 0.5)),
            filled: true,
            fillColor: Colors.white,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: GoOutsColors.border),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: GoOutsColors.border),
            ),
            contentPadding: const EdgeInsets.all(16),
          ),
        ),
      ],
    );
  }

  Widget _buildBookingModeToggle() {
    return Container(
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: GoOutsColors.border),
      ),
      child: Row(
        children: [
          _buildToggleButton(
            'Accept automatically',
            Icons.bolt,
            _bookingMode == 'Accept automatically',
          ),
          _buildToggleButton(
            'Review each request',
            Icons.edit_note,
            _bookingMode == 'Review each request',
          ),
        ],
      ),
    );
  }

  Widget _buildToggleButton(String label, IconData icon, bool isSelected) {
    return Expanded(
      child: GestureDetector(
        onTap: () => setState(() => _bookingMode = label),
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 20),
          decoration: BoxDecoration(
            color: isSelected ? GoOutsColors.teal : Colors.transparent,
            borderRadius: BorderRadius.circular(10),
          ),
          child: Column(
            children: [
              Icon(icon, color: isSelected ? Colors.white : GoOutsColors.navy, size: 24),
              const SizedBox(height: 8),
              Text(
                label,
                textAlign: TextAlign.center,
                style: GoogleFonts.inter(
                  color: isSelected ? Colors.white : GoOutsColors.navy,
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildPolicyList() {
    return Column(
      children: [
        _buildPolicyCard('Flexible', 'Full refund 1 day prior to arrival.'),
        const SizedBox(height: 12),
        _buildPolicyCard('Moderate', 'Full refund 5 days prior to arrival.'),
        const SizedBox(height: 12),
        _buildPolicyCard(
          'Strict',
          'Full refund for cancellations made within 48 hours of booking, if the check-in date is at least 14 days away.',
        ),
      ],
    );
  }

  Widget _buildPolicyCard(String title, String subtitle) {
    final isSelected = _selectedPolicy == title;
    return GestureDetector(
      onTap: () => setState(() => _selectedPolicy = title),
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: GoOutsColors.surface,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: isSelected ? GoOutsColors.teal : GoOutsColors.border,
            width: isSelected ? 2 : 1,
          ),
        ),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    title,
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 16,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    subtitle,
                    style: GoogleFonts.inter(
                      color: GoOutsColors.body,
                      fontSize: 14,
                      height: 1.4,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(width: 12),
            Container(
              width: 24,
              height: 24,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                border: Border.all(
                  color: isSelected ? GoOutsColors.teal : GoOutsColors.border,
                  width: isSelected ? 7 : 2,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildFooter() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: const BoxDecoration(
        color: GoOutsColors.surface,
        border: Border(top: BorderSide(color: Colors.black12, width: 0.5)),
      ),
      child: SafeArea(
        child: ElevatedButton(
          onPressed: () =>
                  Navigator.of(context).pushNamed(HostRoutes.newLegal),
          style: ElevatedButton.styleFrom(
            backgroundColor: GoOutsColors.teal,
            minimumSize: const Size(double.infinity, 56),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            elevation: 0,
          ),
          child: Text(
            'Next step',
            style: GoogleFonts.inter(
              color: Colors.white,
              fontSize: 16,
              fontWeight: FontWeight.w600,
            ),
          ),
        ),
      ),
    );
  }
}
