// Generated by Google Stitch. Source folder: 16-pre_arrival_capture
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';

import 'host_bottom_nav.dart';


class HostPreArrivalCaptureScreen extends StatelessWidget {
  const HostPreArrivalCaptureScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          // Was `leading: const Icon(...)` — a decorative arrow that
          // was NOT tappable. It looked like a back button and did
          // nothing, which is worse than having no arrow at all.
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Dashboard',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'CONDITION RECORD',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.teal,
                      fontSize: 12,
                      fontWeight: FontWeight.w600,
                      letterSpacing: 0.5,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        'Room 1 of 4',
                        style: GoogleFonts.inter(
                          color: GoOutsColors.navy,
                          fontSize: 24,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                      Container(
                        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                        decoration: BoxDecoration(
                          color: GoOutsColors.primary,
                          borderRadius: BorderRadius.circular(20),
                        ),
                        child: Text(
                          'Living Room',
                          style: GoogleFonts.inter(
                            color: Colors.white,
                            fontSize: 12,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            
            // Camera Viewfinder Mock
            Container(
              margin: const EdgeInsets.symmetric(horizontal: 16),
              height: 240,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(12),
                image: const DecorationImage(
                  image: NetworkImage('https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&q=80&w=800'),
                  fit: BoxFit.cover,
                ),
              ),
              child: Stack(
                children: [
                  Positioned(
                    top: 16,
                    right: 16,
                    child: Row(
                      children: [
                        const Icon(Icons.circle, color: GoOutsColors.error, size: 8),
                        const SizedBox(width: 4),
                        Text(
                          'REC',
                          style: GoogleFonts.inter(color: Colors.white, fontSize: 12, fontWeight: FontWeight.w700),
                        ),
                      ],
                    ),
                  ),
                  const Center(
                    child: Icon(Icons.filter_center_focus, color: Colors.white, size: 48),
                  ),
                ],
              ),
            ),
            
            const SizedBox(height: 16),
            
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                _buildCircleButton(Icons.flash_off),
                const SizedBox(width: 40),
                _buildCircleButton(Icons.cameraswitch_outlined),
              ],
            ),
            
            const SizedBox(height: 24),
            
            // Info Card
            Container(
              margin: const EdgeInsets.symmetric(horizontal: 16),
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: const Color(0xFFA5E1F9),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Icon(Icons.info_outline, color: GoOutsColors.navy, size: 24),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      'It is important to photograph your property now. You cannot later claim a room was perfect if you do not have a record of it.',
                      style: GoogleFonts.inter(
                        color: GoOutsColors.navy,
                        fontSize: 14,
                        height: 1.4,
                      ),
                    ),
                  ),
                ],
              ),
            ),
            
            const SizedBox(height: 24),
            
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              child: Text(
                'Room Checklist',
                style: GoogleFonts.inter(
                  color: GoOutsColors.navy,
                  fontSize: 16,
                  fontWeight: FontWeight.w700,
                ),
              ),
            ),
            
            const SizedBox(height: 12),
            
            SizedBox(
              height: 120,
              child: ListView(
                scrollDirection: Axis.horizontal,
                padding: const EdgeInsets.symmetric(horizontal: 16),
                children: [
                  _buildRoomCard('Living Room', true),
                  const SizedBox(width: 12),
                  _buildRoomCard('Kitchen', false),
                  const SizedBox(width: 12),
                  _buildRoomCard('Bedroom', false),
                ],
              ),
            ),
            
            const SizedBox(height: 32),
            
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              child: ElevatedButton(
                onPressed: () {},
                style: ElevatedButton.styleFrom(
                  backgroundColor: GoOutsColors.primary,
                  minimumSize: const Size(double.infinity, 52),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  elevation: 0,
                ),
                child: Text(
                  'Complete Living Room (1/4)',
                  style: GoogleFonts.inter(
                    color: Colors.white,
                    fontSize: 16,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
            ),
            
            const SizedBox(height: 12),
            
            Center(
              child: Text(
                'Photos are timestamped and encrypted for protection.',
                style: GoogleFonts.inter(
                  color: GoOutsColors.body.withValues(alpha: 0.6),
                  fontSize: 12,
                ),
              ),
            ),
            
            const SizedBox(height: 40),
          ],
        ),
      ),
      bottomNavigationBar: const HostBottomNav(current: HostTab.bookings),
    );
  }

  Widget _buildCircleButton(IconData icon) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: const BoxDecoration(
        color: Color(0xFFE5EDFF),
        shape: BoxShape.circle,
      ),
      child: Icon(icon, color: GoOutsColors.navy),
    );
  }

  Widget _buildRoomCard(String name, bool isCompleted) {
    return Container(
      width: 140,
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
        border: isCompleted ? Border.all(color: GoOutsColors.primary, width: 2) : null,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            child: Container(
              decoration: BoxDecoration(
                color: GoOutsColors.tint,
                borderRadius: const BorderRadius.vertical(top: Radius.circular(10)),
              ),
              child: const Center(child: Icon(Icons.camera_alt_outlined, color: GoOutsColors.primary, size: 24)),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  name,
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 13,
                    fontWeight: FontWeight.w600,
                  ),
                ),
                if (isCompleted)
                  const Icon(Icons.check_circle, color: GoOutsColors.primary, size: 16)
                else
                  const Icon(Icons.circle_outlined, color: GoOutsColors.body, size: 16),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
