// Generated by Google Stitch. Source folder: 11-listing_preview
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';


class ListingPreviewScreen extends StatelessWidget {
  const ListingPreviewScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.teal),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Review Listing',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: const EdgeInsets.all(16.0),
              child: Text(
                'Review your property details before going live. All information is correct as of today.',
                style: GoogleFonts.inter(
                  color: GoOutsColors.body,
                  fontSize: 15,
                  height: 1.4,
                ),
              ),
            ),
            _buildImageSection(
              title: 'Cover Photo',
              subtitle: 'Main display image for potential guests',
              imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800',
            ),
            _buildSectionCard(
              title: 'Property Title',
              content: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'The Serene Garden Suite',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.teal,
                      fontSize: 16,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  const SizedBox(height: 16),
                  Row(
                    children: [
                      const Icon(Icons.apartment, size: 20, color: GoOutsColors.teal),
                      const SizedBox(width: 12),
                      Text(
                        'Entire Guest Suite',
                        style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 14),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  Row(
                    children: [
                      const Icon(Icons.people_outline, size: 20, color: GoOutsColors.teal),
                      const SizedBox(width: 12),
                      Text(
                        'Up to 2 Guests',
                        style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 14),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            _buildSectionCard(
              title: 'Pricing',
              content: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  RichText(
                    text: TextSpan(
                      style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 20, fontWeight: FontWeight.w800),
                      children: [
                        const TextSpan(text: '£145'),
                        TextSpan(
                          text: ' / per night',
                          style: GoogleFonts.inter(color: GoOutsColors.body, fontSize: 14, fontWeight: FontWeight.w400),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 16),
                  Container(
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: GoOutsColors.tint.withValues(alpha: 0.5),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Column(
                      children: [
                        _buildPriceRow('Cleaning fee', '£30.00'),
                        const SizedBox(height: 8),
                        _buildPriceRow('Weekend premium', '+15%'),
                      ],
                    ),
                  ),
                ],
              ),
            ),
            _buildSectionCard(
              title: 'Amenities',
              subtitle: 'Essential features provided for guests',
              content: Wrap(
                spacing: 8,
                runSpacing: 8,
                children: [
                  _buildAmenityChip(Icons.wifi, 'Fast Wi-Fi'),
                  _buildAmenityChip(Icons.local_parking, 'Free Parking'),
                  _buildAmenityChip(Icons.kitchen, 'Kitchenette'),
                  _buildAmenityChip(Icons.laptop_mac, 'Workspace'),
                  _buildAmenityChip(Icons.ac_unit, 'Air Con'),
                  _buildAmenityChip(Icons.tv, 'Smart TV'),
                ],
              ),
            ),
            _buildSectionCard(
              title: 'Location Details',
              content: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Oxford, United Kingdom • Near City Centre',
                    style: GoogleFonts.inter(color: GoOutsColors.body, fontSize: 14),
                  ),
                  const SizedBox(height: 16),
                  Container(
                    height: 180,
                    width: double.infinity,
                    decoration: BoxDecoration(
                      color: const Color(0xFFB3E5FC),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Center(
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          const Icon(Icons.location_on, color: GoOutsColors.teal, size: 32),
                          const SizedBox(height: 8),
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                            decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(4)),
                            child: Text(
                              'OX1 2DP',
                              style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 12, fontWeight: FontWeight.w700),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 24),
                  Text(
                    'Nearby Recommended Partners',
                    style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 15, fontWeight: FontWeight.w700),
                  ),
                  const SizedBox(height: 12),
                  Row(
                    children: [
                      Expanded(child: _buildPartnerCard(Icons.coffee, 'The Bean & Leaf', '0.2 miles away')),
                      const SizedBox(width: 12),
                      Expanded(child: _buildPartnerCard(Icons.restaurant, 'Oxford Bistro', '0.5 miles away')),
                    ],
                  ),
                ],
              ),
            ),
            _buildComplianceAlert(),
            const SizedBox(height: 100),
          ],
        ),
      ),
      bottomNavigationBar: _buildBottomButtons(),
    );
  }

  Widget _buildImageSection({required String title, required String subtitle, required String imageUrl}) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [BoxShadow(color: Colors.black.withValues(alpha: 0.02), blurRadius: 10)],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          ClipRRect(
            borderRadius: const BorderRadius.vertical(top: Radius.circular(16)),
            child: Image.network(imageUrl, height: 200, width: double.infinity, fit: BoxFit.cover),
          ),
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(title, style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 16, fontWeight: FontWeight.w700)),
                      const SizedBox(height: 4),
                      Text(subtitle, style: GoogleFonts.inter(color: GoOutsColors.body, fontSize: 13)),
                    ],
                  ),
                ),
                _buildEditButton(),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSectionCard({required String title, String? subtitle, required Widget content}) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [BoxShadow(color: Colors.black.withValues(alpha: 0.02), blurRadius: 10)],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(title, style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 16, fontWeight: FontWeight.w700)),
              _buildEditButton(),
            ],
          ),
          if (subtitle != null) ...[
            const SizedBox(height: 4),
            Text(subtitle, style: GoogleFonts.inter(color: GoOutsColors.body, fontSize: 13)),
          ],
          const SizedBox(height: 16),
          content,
        ],
      ),
    );
  }

  Widget _buildEditButton() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: BoxDecoration(color: const Color(0xFFB3E5FC).withValues(alpha: 0.5), borderRadius: BorderRadius.circular(20)),
      child: Row(
        children: [
          const Icon(Icons.edit, size: 14, color: GoOutsColors.primary),
          const SizedBox(width: 6),
          Text(
            'Edit',
            style: GoogleFonts.inter(color: GoOutsColors.primary, fontSize: 12, fontWeight: FontWeight.w700),
          ),
        ],
      ),
    );
  }

  Widget _buildPriceRow(String label, String value) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(label, style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 14)),
        Text(value, style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 14, fontWeight: FontWeight.w600)),
      ],
    );
  }

  Widget _buildAmenityChip(IconData icon, String label) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(color: const Color(0xFFF1F5F9), borderRadius: BorderRadius.circular(8)),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 16, color: GoOutsColors.teal),
          const SizedBox(width: 8),
          Text(label, style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 13, fontWeight: FontWeight.w500)),
        ],
      ),
    );
  }

  Widget _buildPartnerCard(IconData icon, String name, String distance) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(color: const Color(0xFFF1F5F9), borderRadius: BorderRadius.circular(12)),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: const BoxDecoration(color: GoOutsColors.teal, shape: BoxShape.circle),
            child: Icon(icon, color: Colors.white, size: 16),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(name, style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 12, fontWeight: FontWeight.w700), maxLines: 1, overflow: TextOverflow.ellipsis),
                Text(distance, style: GoogleFonts.inter(color: GoOutsColors.body, fontSize: 11)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildComplianceAlert() {
    return Container(
      margin: const EdgeInsets.all(16),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFFE0F3FB),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.info_outline, color: GoOutsColors.teal, size: 20),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              'By publishing, you agree to our Host Terms of Service and verify that all information provided is accurate and compliant with local regulations.',
              style: GoogleFonts.inter(
                color: const Color(0xFF00668C),
                fontSize: 13,
                height: 1.4,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBottomButtons() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: const BoxDecoration(
        color: GoOutsColors.surface,
        border: Border(top: BorderSide(color: Color(0xFFF1F5F9), width: 1)),
      ),
      child: SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ElevatedButton(
              onPressed: () {},
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF00668C),
                minimumSize: const Size(double.infinity, 56),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                elevation: 0,
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.rocket_launch, color: Colors.white, size: 20),
                  const SizedBox(width: 12),
                  Text(
                    'Publish listing',
                    style: GoogleFonts.inter(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w700),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 12),
            OutlinedButton(
              onPressed: () {},
              style: OutlinedButton.styleFrom(
                backgroundColor: const Color(0xFFB3E5FC).withValues(alpha: 0.5),
                minimumSize: const Size(double.infinity, 56),
                side: BorderSide.none,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              ),
              child: Text(
                'Save as Draft',
                style: GoogleFonts.inter(color: GoOutsColors.primary, fontSize: 16, fontWeight: FontWeight.w700),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
