// Generated by Google Stitch. Source folder: 2-property_address
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import 'host_routes.dart';

import '../../../theme/goouts_colors.dart';


class CreateListingAddressScreen extends StatefulWidget {
  const CreateListingAddressScreen({super.key});

  @override
  State<CreateListingAddressScreen> createState() => _CreateListingAddressScreenState();
}

class _CreateListingAddressScreenState extends State<CreateListingAddressScreen> {
  String _selectedAddress = 'Clarence House';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          // Was `leading: const Icon(...)` — a decorative arrow that
          // was NOT tappable. It looked like a back button and did
          // nothing, which is worse than having no arrow at all.
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Create Listing',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
        actions: [
          TextButton(
            onPressed: () {},
            child: Text(
              'Save & Exit',
              style: GoogleFonts.inter(
                color: GoOutsColors.primary,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          const SizedBox(width: 8),
        ],
      ),
      body: Column(
        children: [
          _buildProgressBar(),
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Where is your place located?',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 24,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Guests will only get your exact address once they have booked a reservation.',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.body,
                      fontSize: 15,
                    ),
                  ),
                  const SizedBox(height: 32),
                  _buildPostcodeSection(),
                  const SizedBox(height: 32),
                  Text(
                    'Select an address',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  const SizedBox(height: 8),
                  _buildAddressList(),
                  const SizedBox(height: 24),
                  _buildManualEntryLink(),
                ],
              ),
            ),
          ),
          _buildFooter(),
        ],
      ),
    );
  }

  Widget _buildProgressBar() {
    return Container(
      width: double.infinity,
      height: 4,
      color: GoOutsColors.primary.withValues(alpha: 0.1),
      child: FractionallySizedBox(
        alignment: Alignment.centerLeft,
        widthFactor: 0.25, // Step 1 of 4
        child: Container(color: GoOutsColors.primary),
      ),
    );
  }

  Widget _buildPostcodeSection() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Expanded(
                child: Container(
                  height: 52,
                  padding: const EdgeInsets.symmetric(horizontal: 16),
                  decoration: BoxDecoration(
                    color: GoOutsColors.background,
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(color: Colors.black12),
                  ),
                  alignment: Alignment.centerLeft,
                  child: Text(
                    'SW1A 1AA',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 16,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 12),
              ElevatedButton(
                onPressed: () {},
                style: ElevatedButton.styleFrom(
                  backgroundColor: GoOutsColors.primary,
                  minimumSize: const Size(120, 52),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  elevation: 0,
                ),
                child: Text(
                  'Find address',
                  style: GoogleFonts.inter(
                    color: Colors.white,
                    fontSize: 16,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              const Icon(Icons.info_outline, color: GoOutsColors.body, size: 16),
              const SizedBox(width: 8),
              Text(
                'We will work out the rest from this',
                style: GoogleFonts.inter(
                  color: GoOutsColors.body,
                  fontSize: 13,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildAddressList() {
    final addresses = [
      {'name': 'Buckingham Palace', 'details': 'London, SW1A 1AA'},
      {'name': 'Clarence House', 'details': 'St. James\'s Palace, London, SW1A 1BA'},
      {'name': '10 Downing Street', 'details': 'London, SW1A 2AA'},
    ];

    return Container(
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        children: addresses.asMap().entries.map((entry) {
          final isLast = entry.key == addresses.length - 1;
          final address = entry.value;
          final isSelected = _selectedAddress == address['name'];

          return Column(
            children: [
              GestureDetector(
                onTap: () => setState(() => _selectedAddress = address['name']!),
                child: Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
                  child: Row(
                    children: [
                      Icon(
                        isSelected ? Icons.radio_button_checked : Icons.radio_button_off,
                        color: isSelected ? GoOutsColors.primary : GoOutsColors.body.withValues(alpha: 0.3),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              address['name']!,
                              style: GoogleFonts.inter(
                                color: GoOutsColors.navy,
                                fontSize: 15,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                            Text(
                              address['details']!,
                              style: GoogleFonts.inter(
                                color: GoOutsColors.body,
                                fontSize: 13,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              if (!isLast) const Divider(height: 1, color: GoOutsColors.background, indent: 56),
            ],
          );
        }).toList(),
      ),
    );
  }

  Widget _buildManualEntryLink() {
    return TextButton.icon(
      onPressed: () {},
      icon: const Icon(Icons.edit_location_alt_outlined, color: GoOutsColors.primary, size: 20),
      label: Text(
        'Enter address manually',
        style: GoogleFonts.inter(
          color: GoOutsColors.primary,
          fontSize: 16,
          fontWeight: FontWeight.w600,
          decoration: TextDecoration.underline,
        ),
      ),
    );
  }

  Widget _buildFooter() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: const BoxDecoration(
        color: GoOutsColors.surface,
        border: Border(top: BorderSide(color: Colors.black12, width: 0.5)),
      ),
      child: SafeArea(
        child: Row(
          children: [
            TextButton(
              onPressed: () {},
              child: Text(
                'Back',
                style: GoogleFonts.inter(
                  color: GoOutsColors.navy,
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
            const Spacer(),
            ElevatedButton(
              onPressed: () =>
                  Navigator.of(context).pushNamed(HostRoutes.newLocation),
              style: ElevatedButton.styleFrom(
                backgroundColor: GoOutsColors.primary,
                minimumSize: const Size(140, 52),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                elevation: 0,
              ),
              child: Text(
                'Next',
                style: GoogleFonts.inter(
                  color: Colors.white,
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
