// Generated by Google Stitch. Source folder: 13-booking_requests
// WIRED 6 August 2026 — the first host screen connected to real data.
//
// ── WHAT WAS REMOVED FROM THE STITCH DESIGN, AND WHY ────────────────────────
//
// "Verified" badge next to every guest name. DELETED.
//   /public_profiles deliberately exposes displayName, photoUrl and
//   inFamilyGroup ONLY. kycStatus is NOT published, precisely so one user
//   cannot learn another's identity-check state. Rendering a Verified badge
//   would either need that field exposed — undoing a security decision made on
//   3 August — or be decoration asserting something we have not checked. A
//   host deciding whether to let a stranger into their home is exactly the
//   wrong person to show an unbacked trust signal.
//
// "HIGH DEMAND DATE" flag. DELETED.
//   No demand signal exists. It was invented copy. Telling a host their dates
//   are in demand, with nothing behind it, pressures them toward accepting.
//
// "3 Pending" hardcoded count. Now the real count.
//
// ── THE ONE THAT MATTERS MOST ───────────────────────────────────────────────
//
// The card said "Total Payout £580.00" against a guest total. Those are
// different numbers — commission sits between them. Showing a host the
// GUEST'S total labelled as their payout overstates what they receive by the
// commission rate on every single row.
//
// This renders pricing.hostPayout, which the server calculated, and shows the
// guest total separately and quietly so the two can never be confused.
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

// money.dart is NOT imported. Pence arrives already typed on
// HostBookingRequest, so the type is never named here.
import '../services/stay_host_service.dart';
import 'host_routes.dart';

import '../../../theme/goouts_colors.dart';
import 'friendly_error.dart';


class BookingRequestsScreen extends StatefulWidget {
  const BookingRequestsScreen({super.key});

  @override
  State<BookingRequestsScreen> createState() => _BookingRequestsScreenState();
}

class _BookingRequestsScreenState extends State<BookingRequestsScreen> {
  List<HostBookingRequest> _requests = const [];

  /// guestUid -> {displayName, photoUrl}, from /public_profiles.
  final Map<String, Map<String, dynamic>> _profiles = {};

  bool _loading = true;
  String? _error;

  /// bookingIds currently being accepted or declined. Per-row, not a single
  /// screen-wide flag: a host answering one request must not have every other
  /// button disabled while it runs.
  final Set<String> _busy = {};

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() {
      _loading = true;
      _error = null;
    });
    try {
      final list = await StayHostService.instance.pendingRequests();

      // Guest names come from /public_profiles, which any signed-in user may
      // read. /users may NOT be read by a host — that was closed on 3 August.
      final ids = list.map((r) => r.guestUid).where((s) => s.isNotEmpty).toSet();
      final fetched = <String, Map<String, dynamic>>{};
      if (ids.isNotEmpty) {
        // whereIn caps at 30. A host with more than 30 pending requests is not
        // a scenario worth paging for yet, but silently dropping the 31st
        // would be, so take() is explicit rather than accidental.
        final snap = await FirebaseFirestore.instance
            .collection('public_profiles')
            .where(FieldPath.documentId, whereIn: ids.take(30).toList())
            .get();
        for (final d in snap.docs) {
          fetched[d.id] = d.data();
        }
      }

      if (!mounted) return;
      setState(() {
        _requests = list;
        _profiles
          ..clear()
          ..addAll(fetched);
        _loading = false;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _error = 'Could not load your requests. Please try again.';
        _loading = false;
      });
    }
  }

  Future<void> _accept(HostBookingRequest r) async {
    setState(() => _busy.add(r.bookingId));
    try {
      final didAccept = await StayHostService.instance.accept(r.bookingId);
      if (!mounted) return;
      _toast(didAccept
          ? 'Booking confirmed. The guest has been notified.'
          : 'That booking was already confirmed.');
      await _load();
    } catch (e) {
      if (!mounted) return;
      _toast(_message(e), isError: true);
    } finally {
      if (mounted) setState(() => _busy.remove(r.bookingId));
    }
  }

  Future<void> _decline(HostBookingRequest r) async {
    final reason = await _askReason();
    if (reason == null) return; // cancelled the dialog, not the booking

    // The dialog is an await like any other. If this screen is disposed while
    // it is open, setState below throws on a dead State. Easy to miss because
    // showDialog does not look like a network call.
    if (!mounted) return;

    setState(() => _busy.add(r.bookingId));
    try {
      final freed =
          await StayHostService.instance.decline(r.bookingId, reason: reason);
      if (!mounted) return;
      // Naming the nights released is deliberate. Freeing the calendar is the
      // part of a decline that silently fails, so the host is shown that it
      // actually happened rather than being asked to assume it.
      _toast(freed > 0
          ? 'Request declined. $freed ${freed == 1 ? 'night is' : 'nights are'} '
              'available to book again.'
          : 'Request declined.');
      await _load();
    } catch (e) {
      if (!mounted) return;
      _toast(_message(e), isError: true);
    } finally {
      if (mounted) setState(() => _busy.remove(r.bookingId));
    }
  }

  /// The reason is stored on the booking for the record. It is NOT shown to
  /// the guest — see stay_host.js.
  Future<String?> _askReason() async {
    final ctrl = TextEditingController();
    final result = await showDialog<String>(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: Text('Decline this request',
            style: GoogleFonts.inter(fontWeight: FontWeight.w700)),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'The dates will become available for other guests straight away.',
              style: GoogleFonts.inter(fontSize: 13, color: GoOutsColors.body),
            ),
            const SizedBox(height: 12),
            TextField(
              controller: ctrl,
              maxLines: 2,
              maxLength: 500,
              decoration: const InputDecoration(
                hintText: 'Reason (for your records, optional)',
                border: OutlineInputBorder(),
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(),
            child: const Text('Keep request'),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
                backgroundColor: GoOutsColors.danger,
                foregroundColor: Colors.white),
            onPressed: () => Navigator.of(dialogContext).pop(ctrl.text.trim()),
            child: const Text('Decline'),
          ),
        ],
      ),
    );
    ctrl.dispose();
    return result;
  }

  String _message(Object e) {
    // The server sends a readable sentence for the cases a host can act on —
    // already answered, check-in date passed. Surface it rather than replacing
    // it with something generic that explains nothing.
    // Was e.toString() + substring, which appended the whole Dart stack trace
    // to the toast. See friendly_error.dart.
    return friendlyError(e, fallback: 'Something went wrong. Please try again.');
  }

  void _toast(String msg, {bool isError = false}) {
    ScaffoldMessenger.of(context).showSnackBar(SnackBar(
      content: Text(msg),
      backgroundColor: isError ? GoOutsColors.danger : GoOutsColors.success,
    ));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.navy),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text('Booking Requests',
            style: GoogleFonts.inter(
                color: GoOutsColors.navy,
                fontSize: 20,
                fontWeight: FontWeight.w700)),
        actions: [
          if (!_loading && _requests.isNotEmpty)
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 12),
                alignment: Alignment.center,
                decoration: BoxDecoration(
                  color: const Color(0xFF00668C),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Text('${_requests.length} Pending',
                    style: GoogleFonts.inter(
                        color: Colors.white,
                        fontSize: 12,
                        fontWeight: FontWeight.w600)),
              ),
            ),
        ],
      ),
      body: RefreshIndicator(
        onRefresh: _load,
        child: _body(),
      ),
    );
  }

  Widget _body() {
    if (_loading) {
      return const Center(child: CircularProgressIndicator());
    }
    if (_error != null) {
      return _state(Icons.wifi_off_rounded, 'Could not load requests', _error!,
          retry: true);
    }
    if (_requests.isEmpty) {
      return _state(Icons.inbox_outlined, 'No requests waiting',
          'When a guest asks to book one of your properties, it will appear '
          'here for you to accept or decline.');
    }

    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        Text('Review Enquiries',
            style: GoogleFonts.inter(
                color: GoOutsColors.navy,
                fontSize: 22,
                fontWeight: FontWeight.w700)),
        const SizedBox(height: 4),
        Text(
          'Dates are held while you decide, so nobody else can book them.',
          style: GoogleFonts.inter(fontSize: 13, color: GoOutsColors.body),
        ),
        const SizedBox(height: 16),
        ..._requests.map(_card),
        const SizedBox(height: 24),
      ],
    );
  }

  Widget _state(IconData icon, String title, String body, {bool retry = false}) =>
      ListView(
        // ListView not Column, so RefreshIndicator still works when empty —
        // pull to refresh needs a scrollable, and an empty state is exactly
        // when somebody pulls.
        physics: const AlwaysScrollableScrollPhysics(),
        padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 72),
        children: [
          Icon(icon, size: 44, color: Colors.grey.shade400),
          const SizedBox(height: 16),
          Text(title,
              textAlign: TextAlign.center,
              style: GoogleFonts.inter(
                  fontSize: 17,
                  fontWeight: FontWeight.w700,
                  color: GoOutsColors.navy)),
          const SizedBox(height: 8),
          Text(body,
              textAlign: TextAlign.center,
              style: GoogleFonts.inter(
                  fontSize: 13.5, color: GoOutsColors.onSurfaceVariant)),
          if (retry) ...[
            const SizedBox(height: 20),
            Center(
              child: OutlinedButton(
                  onPressed: _load, child: const Text('Try again')),
            ),
          ],
        ],
      );

  String _dates(HostBookingRequest r) {
    const m = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    String f(DateTime? d) => d == null ? '?' : '${d.day} ${m[d.month - 1]}';
    return '${f(r.checkIn)} - ${f(r.checkOut)}';
  }

  Widget _card(HostBookingRequest r) {
    final p = _profiles[r.guestUid];
    // "GoOuts Guest" rather than a blank or the raw uid. A profile can be
    // missing legitimately — the mirror is written by a Cloud Function and may
    // not have caught up for an account created seconds ago.
    final name = (p?['displayName'] as String?)?.trim().isNotEmpty == true
        ? p!['displayName'] as String
        : 'GoOuts Guest';
    final photo = (p?['photoUrl'] as String?) ?? '';
    final busy = _busy.contains(r.bookingId);

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
              color: Colors.black.withValues(alpha: 0.02),
              blurRadius: 10,
              offset: const Offset(0, 4)),
        ],
      ),
      child: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(16),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                CircleAvatar(
                  radius: 28,
                  backgroundColor: GoOutsColors.infoBg,
                  backgroundImage: photo.isNotEmpty ? NetworkImage(photo) : null,
                  child: photo.isEmpty
                      ? const Icon(Icons.person_outline,
                          color: GoOutsColors.primary)
                      : null,
                ),
                const SizedBox(width: 14),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // No "Verified" badge. See the file header.
                      Text(name,
                          style: GoogleFonts.inter(
                              color: GoOutsColors.navy,
                              fontSize: 16,
                              fontWeight: FontWeight.w700)),
                      const SizedBox(height: 4),
                      Text(
                        '${_dates(r)}  ·  ${r.nights} '
                        '${r.nights == 1 ? 'night' : 'nights'}',
                        style: GoogleFonts.inter(
                            fontSize: 13, color: GoOutsColors.body),
                      ),
                      Text(
                        '${r.countedGuests} '
                        '${r.countedGuests == 1 ? 'guest' : 'guests'}'
                        '${r.infants > 0 ? ' + ${r.infants} infant${r.infants == 1 ? '' : 's'}' : ''}',
                        style: GoogleFonts.inter(
                            fontSize: 13, color: GoOutsColors.onSurfaceVariant),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),

          // ── Money. The host's number is the big one. ────────────────────
          Container(
            width: double.infinity,
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            color: GoOutsColors.infoBg,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    Text('You receive',
                        style: GoogleFonts.inter(
                            fontSize: 12.5, color: GoOutsColors.body)),
                    const Spacer(),
                    Text(r.hostPayout.compact,
                        style: GoogleFonts.inter(
                            fontSize: 20,
                            fontWeight: FontWeight.w800,
                            color: GoOutsColors.navy)),
                  ],
                ),
                const SizedBox(height: 2),
                Text(
                  'Guest pays ${r.guestTotal.compact}. '
                  'Commission is already deducted.',
                  style: GoogleFonts.inter(
                      fontSize: 11.5, color: GoOutsColors.onSurfaceVariant),
                ),
                if (!r.paymentTaken) ...[
                  const SizedBox(height: 6),
                  Text(
                    'No payment has been taken yet.',
                    style: GoogleFonts.inter(
                        fontSize: 11.5,
                        fontWeight: FontWeight.w600,
                        color: GoOutsColors.body),
                  ),
                ],
              ],
            ),
          ),

          Padding(
            padding: const EdgeInsets.all(12),
            child: Row(
              children: [
                Expanded(
                  child: OutlinedButton(
                    onPressed: busy ? null : () => _decline(r),
                    style: OutlinedButton.styleFrom(
                      minimumSize: const Size(0, 48),
                      foregroundColor: GoOutsColors.danger,
                      side: const BorderSide(color: GoOutsColors.border),
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12)),
                    ),
                    child: const Text('Decline'),
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  flex: 2,
                  child: ElevatedButton(
                    onPressed: busy ? null : () => _accept(r),
                    style: ElevatedButton.styleFrom(
                      minimumSize: const Size(0, 48),
                      backgroundColor: GoOutsColors.primary,
                      foregroundColor: Colors.white,
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12)),
                      elevation: 0,
                    ),
                    child: busy
                        ? const SizedBox(
                            width: 18,
                            height: 18,
                            child: CircularProgressIndicator(
                                strokeWidth: 2, color: Colors.white))
                        : const Text('Accept'),
                  ),
                ),
              ],
            ),
          ),

          // ── FULL DETAILS ──────────────────────────────────────────────
          //
          // Added 8 August 2026. Screen 15 was routed and reachable from
          // nothing, so a host could accept or decline but never see the
          // cancellation terms, the exact payout breakdown, or (once
          // accepted) the route to photographing the rooms before arrival.
          //
          // PASS THE ID, NEVER THE OBJECT — a route argument holding a
          // booking breaks deep links and state restoration after iOS kills
          // the app.
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 12),
            child: Align(
              alignment: Alignment.centerLeft,
              child: TextButton.icon(
                onPressed: () => Navigator.of(context).pushNamed(
                  HostRoutes.booking,
                  arguments: r.bookingId,
                ),
                icon: const Icon(Icons.receipt_long_outlined, size: 17),
                label: const Text('See full details'),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
