// Generated by Google Stitch. Source folder: 20-host_earnings
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';

import 'host_bottom_nav.dart';


class HostEarningsScreen extends StatelessWidget {
  const HostEarningsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Earnings',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildEarningsOverview(),
            const SizedBox(height: 24),
            _buildPayoutBreakdown(),
            const SizedBox(height: 24),
            Text(
              'How would you like to be paid?',
              style: GoogleFonts.inter(
                color: GoOutsColors.navy,
                fontSize: 16,
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 16),
            _buildPayoutMethods(),
            const SizedBox(height: 24),
            _buildConfirmButton(),
            const SizedBox(height: 32),
            _buildRecentPayoutsHeader(),
            const SizedBox(height: 12),
            _buildRecentPayoutsList(),
            const SizedBox(height: 40),
          ],
        ),
      ),
      bottomNavigationBar: const HostBottomNav(current: HostTab.earnings),
    );
  }

  Widget _buildEarningsOverview() {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.02),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Last 6 Months',
                style: GoogleFonts.inter(
                  color: GoOutsColors.body,
                  fontSize: 14,
                  fontWeight: FontWeight.w500,
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                decoration: BoxDecoration(
                  color: const Color(0xFFE0F7FA),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Row(
                  children: [
                    const Icon(Icons.trending_up, size: 14, color: GoOutsColors.primary),
                    const SizedBox(width: 4),
                    Text(
                      '8% vs LY',
                      style: GoogleFonts.inter(
                        color: GoOutsColors.primary,
                        fontSize: 12,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            '£14,840',
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 32,
              fontWeight: FontWeight.w800,
            ),
          ),
          const SizedBox(height: 32),
          // Simple Bar Chart Mockup
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              _buildChartBar('MAR', 0.4),
              _buildChartBar('APR', 0.6),
              _buildChartBar('MAY', 0.5),
              _buildChartBar('JUN', 0.7),
              _buildChartBar('JUL', 0.8),
              _buildChartBar('AUG', 1.0, isActive: true),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildChartBar(String month, double heightFactor, {bool isActive = false}) {
    return Column(
      children: [
        Container(
          width: 32,
          height: 80 * heightFactor,
          decoration: BoxDecoration(
            color: isActive ? GoOutsColors.primary : const Color(0xFFE2E8F0),
            borderRadius: BorderRadius.circular(4),
          ),
        ),
        const SizedBox(height: 8),
        Text(
          month,
          style: GoogleFonts.inter(
            color: isActive ? GoOutsColors.navy : GoOutsColors.onSurfaceVariant,
            fontSize: 10,
            fontWeight: isActive ? FontWeight.w700 : FontWeight.w500,
          ),
        ),
      ],
    );
  }

  Widget _buildPayoutBreakdown() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Payout breakdown',
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 16,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 16),
          _buildBreakdownRow('Gross Earnings', '£3,200.00'),
          const SizedBox(height: 12),
          _buildBreakdownRow('Commission (15%)', '-£480.00', isNegative: true),
          const Padding(
            padding: EdgeInsets.symmetric(vertical: 16),
            child: Divider(height: 1, color: Color(0xFFF1F5F9)),
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Net Earnings',
                style: GoogleFonts.inter(
                  color: GoOutsColors.navy,
                  fontSize: 16,
                  fontWeight: FontWeight.w700,
                ),
              ),
              Text(
                '£2,720.00',
                style: GoogleFonts.inter(
                  color: GoOutsColors.primary,
                  fontSize: 20,
                  fontWeight: FontWeight.w800,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildBreakdownRow(String label, String value, {bool isNegative = false}) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          label,
          style: GoogleFonts.inter(
            color: GoOutsColors.body,
            fontSize: 14,
          ),
        ),
        Text(
          value,
          style: GoogleFonts.inter(
            color: isNegative ? const Color(0xFFEF4444) : GoOutsColors.navy,
            fontSize: 14,
            fontWeight: FontWeight.w600,
          ),
        ),
      ],
    );
  }

  Widget _buildPayoutMethods() {
    return Column(
      children: [
        _buildMethodCard(
          icon: Icons.account_balance_outlined,
          title: 'Cash to bank account',
          subtitle: 'Standard 3-5 day processing',
          amount: '£2,720.00',
          isSelected: false,
        ),
        const SizedBox(height: 12),
        _buildMethodCard(
          icon: Icons.stars_outlined,
          title: 'GoOuts Credit',
          subtitle: '+ £280.00 extra value added',
          amount: '£3,000.00',
          isSelected: true,
          tag: 'BEST VALUE',
          extraInfo: 'Optional: Use this at any GoOuts partner for 10% more value. Instant availability.',
        ),
      ],
    );
  }

  Widget _buildMethodCard({
    required IconData icon,
    required String title,
    required String subtitle,
    required String amount,
    required bool isSelected,
    String? tag,
    String? extraInfo,
  }) {
    return Container(
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: isSelected ? GoOutsColors.primary : Colors.transparent,
          width: 2,
        ),
      ),
      child: Column(
        children: [
          if (tag != null)
            Align(
              alignment: Alignment.topRight,
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                decoration: const BoxDecoration(
                  color: Color(0xFF00668C),
                  borderRadius: BorderRadius.only(
                    bottomLeft: Radius.circular(12),
                    topRight: Radius.circular(14),
                  ),
                ),
                child: Text(
                  tag,
                  style: GoogleFonts.inter(
                    color: Colors.white,
                    fontSize: 10,
                    fontWeight: FontWeight.w800,
                    letterSpacing: 0.5,
                  ),
                ),
              ),
            ),
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: const BoxDecoration(color: GoOutsColors.tint, shape: BoxShape.circle),
                  child: Icon(icon, color: GoOutsColors.primary, size: 24),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        title,
                        style: GoogleFonts.inter(
                          color: GoOutsColors.navy,
                          fontSize: 15,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                      const SizedBox(height: 2),
                      Text(
                        subtitle,
                        style: GoogleFonts.inter(
                          color: GoOutsColors.onSurfaceVariant,
                          fontSize: 13,
                        ),
                      ),
                    ],
                  ),
                ),
                Text(
                  amount,
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 16,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ],
            ),
          ),
          if (extraInfo != null)
            Container(
              margin: const EdgeInsets.all(12),
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: GoOutsColors.tint,
                borderRadius: BorderRadius.circular(8),
              ),
              child: Text(
                extraInfo,
                style: GoogleFonts.inter(
                  color: const Color(0xFF00668C),
                  fontSize: 12,
                  height: 1.4,
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildConfirmButton() {
    return ElevatedButton(
      onPressed: () {},
      style: ElevatedButton.styleFrom(
        backgroundColor: const Color(0xFF00668C),
        minimumSize: const Size(double.infinity, 56),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        elevation: 0,
      ),
      child: Text(
        'Confirm Payout Method',
        style: GoogleFonts.inter(
          color: Colors.white,
          fontSize: 16,
          fontWeight: FontWeight.w700,
        ),
      ),
    );
  }

  Widget _buildRecentPayoutsHeader() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          'Recent Payouts',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 16,
            fontWeight: FontWeight.w700,
          ),
        ),
        TextButton(
          onPressed: () {},
          child: Text(
            'View All',
            style: GoogleFonts.inter(
              color: GoOutsColors.primary,
              fontWeight: FontWeight.w600,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildRecentPayoutsList() {
    final payouts = [
      {'title': 'Seaside Retreat', 'date': '12 Aug 2023', 'method': 'Bank Transfer', 'amount': '£1,420.00', 'image': 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=200'},
      {'title': 'City Center Loft', 'date': '28 Jul 2023', 'method': 'GoOuts Credit', 'amount': '£850.00', 'image': 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=200'},
      {'title': 'Forest Cabin', 'date': '15 Jul 2023', 'method': 'Bank Transfer', 'amount': '£2,100.00', 'image': 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=200'},
    ];

    return Container(
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
      ),
      child: ListView.separated(
        shrinkWrap: true,
        physics: const NeverScrollableScrollPhysics(),
        itemCount: payouts.length,
        separatorBuilder: (context, index) => const Divider(height: 1, color: Color(0xFFF1F5F9)),
        itemBuilder: (context, index) {
          final payout = payouts[index];
          return Padding(
            padding: const EdgeInsets.all(16.0),
            child: Row(
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(8),
                  child: Image.network(
                    payout['image']!,
                    width: 56,
                    height: 56,
                    fit: BoxFit.cover,
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        payout['title']!,
                        style: GoogleFonts.inter(
                          color: GoOutsColors.navy,
                          fontSize: 14,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                      const SizedBox(height: 2),
                      Text(
                        '${payout['date']} • ${payout['method']}',
                        style: GoogleFonts.inter(
                          color: GoOutsColors.onSurfaceVariant,
                          fontSize: 12,
                        ),
                      ),
                    ],
                  ),
                ),
                Text(
                  payout['amount']!,
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 15,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}
