// Generated by Google Stitch. Source folder: 5-amenities_selection
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import 'host_routes.dart';

import '../../../theme/goouts_colors.dart';


// Icons.detector_smoke_outlined and Icons.refrigerator_outlined DO NOT EXIST.
// Stitch invented both names. Replaced with Icons.sensors and Icons.ac_unit,
// which are base Material icons and cannot disappear. Note kitchen_outlined,
// wifi_outlined and the rest all resolve — only these two were fabricated, so
// the _outlined suffix is not the problem and should not be stripped wholesale.
class AmenitiesSelectionScreen extends StatefulWidget {
  const AmenitiesSelectionScreen({super.key});

  @override
  State<AmenitiesSelectionScreen> createState() => _AmenitiesSelectionScreenState();
}

class _AmenitiesSelectionScreenState extends State<AmenitiesSelectionScreen> {
  // Mock state for selected amenities
  final Set<String> _selectedAmenities = {'Bathtub', 'Washer', 'TV', 'Wifi', 'Kitchen'};

  void _toggleAmenity(String label) {
    setState(() {
      if (_selectedAmenities.contains(label)) {
        _selectedAmenities.remove(label);
      } else {
        _selectedAmenities.add(label);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.teal),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'List your property',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
        actions: [
          TextButton(
            onPressed: () {},
            child: Text(
              'Save & exit',
              style: GoogleFonts.inter(
                color: GoOutsColors.teal,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ],
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildStepIndicator(),
            Padding(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Tell guests what your place has to offer',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 22,
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'You can add more amenities after you publish your listing.',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.body,
                      fontSize: 15,
                    ),
                  ),
                  const SizedBox(height: 32),
                  
                  _buildCategory('Bathroom', [
                    _buildAmenityItem(Icons.bathtub_outlined, 'Bathtub'),
                    _buildAmenityItem(Icons.dry_cleaning_outlined, 'Hair dryer'),
                    _buildAmenityItem(Icons.sanitizer_outlined, 'Shampoo'),
                  ]),
                  
                  _buildCategory('Bedroom and laundry', [
                    _buildAmenityItem(Icons.local_laundry_service_outlined, 'Washer'),
                    _buildAmenityItem(Icons.checkroom_outlined, 'Essentials (Towels, sheets, etc.)'),
                    _buildAmenityItem(Icons.accessibility_new_outlined, 'Hangers'),
                    _buildAmenityItem(Icons.iron_outlined, 'Iron'),
                  ]),
                  
                  _buildCategory('Entertainment', [
                    _buildAmenityItem(Icons.tv_outlined, 'TV'),
                    _buildAmenityItem(Icons.menu_book_outlined, 'Books and reading material'),
                  ]),
                  
                  _buildCategory('Family', [
                    _buildAmenityItem(Icons.crib_outlined, 'Cot'),
                    _buildAmenityItem(Icons.chair_alt_outlined, 'High chair'),
                  ]),
                  
                  _buildCategory('Heating and cooling', [
                    _buildAmenityItem(Icons.ac_unit_outlined, 'Air conditioning'),
                    _buildAmenityItem(Icons.fireplace_outlined, 'Indoor fireplace'),
                    _buildAmenityItem(Icons.heat_pump_outlined, 'Heating'),
                  ]),
                  
                  _buildCategory('Home safety', [
                    _buildAmenityItem(Icons.sensors, 'Smoke alarm'),
                    _buildAmenityItem(Icons.co2_outlined, 'Carbon monoxide alarm'),
                    _buildAmenityItem(Icons.fire_extinguisher_outlined, 'Fire extinguisher'),
                    _buildAmenityItem(Icons.medical_services_outlined, 'First aid kit'),
                  ]),
                  
                  _buildCategory('Internet and office', [
                    _buildAmenityItem(Icons.wifi_outlined, 'Wifi'),
                    _buildAmenityItem(Icons.computer_outlined, 'Dedicated workspace'),
                  ]),
                  
                  _buildCategory('Kitchen and dining', [
                    _buildAmenityItem(Icons.kitchen_outlined, 'Kitchen'),
                    _buildAmenityItem(Icons.ac_unit, 'Refrigerator'),
                    _buildAmenityItem(Icons.microwave_outlined, 'Microwave'),
                    _buildAmenityItem(Icons.soup_kitchen_outlined, 'Cooking basics'),
                  ]),
                  
                  _buildCategory('Outdoor', [
                    _buildAmenityItem(Icons.deck_outlined, 'Patio or balcony'),
                    _buildAmenityItem(Icons.grass_outlined, 'Backyard'),
                  ]),
                  
                  _buildCategory('Parking and facilities', [
                    _buildAmenityItem(Icons.local_parking_outlined, 'Free parking on premises'),
                    _buildAmenityItem(Icons.elevator_outlined, 'Lift'),
                  ]),
                  
                  const SizedBox(height: 40),
                ],
              ),
            ),
          ],
        ),
      ),
      bottomNavigationBar: _buildBottomNav(),
    );
  }

  Widget _buildStepIndicator() {
    return Container(
      padding: const EdgeInsets.fromLTRB(16, 20, 16, 12),
      color: GoOutsColors.surface,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Step 3 of 5',
                style: GoogleFonts.inter(
                  color: GoOutsColors.body,
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                ),
              ),
              Text(
                'Amenities',
                style: GoogleFonts.inter(
                  color: GoOutsColors.body,
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          ClipRRect(
            borderRadius: BorderRadius.circular(2),
            child: const LinearProgressIndicator(
              value: 0.6,
              backgroundColor: Color(0xFFDCE6FF),
              valueColor: AlwaysStoppedAnimation<Color>(GoOutsColors.teal),
              minHeight: 4,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildCategory(String title, List<Widget> items) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.only(top: 24, bottom: 12),
          child: Text(
            title,
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 16,
              fontWeight: FontWeight.w700,
            ),
          ),
        ),
        Column(
          children: items,
        ),
      ],
    );
  }

  Widget _buildAmenityItem(IconData icon, String label) {
    final isSelected = _selectedAmenities.contains(label);
    return GestureDetector(
      onTap: () => _toggleAmenity(label),
      child: Container(
        margin: const EdgeInsets.only(bottom: 8),
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: GoOutsColors.surface,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: isSelected ? GoOutsColors.primary : GoOutsColors.border.withValues(alpha: 0.5),
            width: isSelected ? 2 : 1,
          ),
        ),
        child: Row(
          children: [
            Icon(icon, color: isSelected ? GoOutsColors.primary : GoOutsColors.navy, size: 22),
            const SizedBox(width: 16),
            Expanded(
              child: Text(
                label,
                style: GoogleFonts.inter(
                  color: GoOutsColors.navy,
                  fontSize: 15,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
            Container(
              width: 24,
              height: 24,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                border: Border.all(
                  color: isSelected ? GoOutsColors.primary : GoOutsColors.border,
                  width: 2,
                ),
                color: isSelected ? GoOutsColors.primary : Colors.transparent,
              ),
              child: isSelected 
                ? const Icon(Icons.check, size: 16, color: Colors.white)
                : null,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildBottomNav() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: const BoxDecoration(
        color: GoOutsColors.surface,
        border: Border(top: BorderSide(color: Color(0xFFF1F5F9), width: 1)),
      ),
      child: SafeArea(
        child: Row(
          children: [
            TextButton(
              onPressed: () {},
              child: Row(
                children: [
                  const Icon(Icons.chevron_left, color: GoOutsColors.teal),
                  Text(
                    'Back',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.teal,
                      fontSize: 16,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ],
              ),
            ),
            const Spacer(),
            ElevatedButton(
              onPressed: () =>
                  Navigator.of(context).pushNamed(HostRoutes.newPhotos),
              style: ElevatedButton.styleFrom(
                backgroundColor: GoOutsColors.teal,
                minimumSize: const Size(160, 56),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                elevation: 0,
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text(
                    'Continue',
                    style: GoogleFonts.inter(
                      color: Colors.white,
                      fontSize: 16,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(width: 8),
                  const Icon(Icons.chevron_right, color: Colors.white),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
