// Generated by Google Stitch. Source folder: 19-claim_details
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';

import 'host_bottom_nav.dart';


class ClaimDetailsScreen extends StatefulWidget {
  const ClaimDetailsScreen({super.key});

  @override
  State<ClaimDetailsScreen> createState() => _ClaimDetailsScreenState();
}

class _ClaimDetailsScreenState extends State<ClaimDetailsScreen> {
  final TextEditingController _costController = TextEditingController();
  final TextEditingController _ageController = TextEditingController(text: '7');
  final TextEditingController _lifeController = TextEditingController(text: '10');
  
  double _calculatedPayout = 0.0;

  void _calculatePayout() {
    final double? cost = double.tryParse(_costController.text);
    final double? age = double.tryParse(_ageController.text);
    final double? totalLife = double.tryParse(_lifeController.text);

    if (cost != null && age != null && totalLife != null && totalLife > 0) {
      setState(() {
        // Simple indemnity calculation: cost * (remaining life / total life)
        double remainingLife = totalLife - age;
        if (remainingLife < 0) remainingLife = 0;
        _calculatedPayout = cost * (remainingLife / totalLife);
      });
    } else {
      setState(() {
        _calculatedPayout = 0.0;
      });
    }
  }


  // Added on import, 4 August 2026. Stitch does not generate dispose().
  //
  // A TextEditingController holds a listener list and is not garbage collected
  // while the framework still references it. Without this, every push of this
  // screen leaks — and iOS kills this app for memory with no stack trace, which
  // has already happened once on the consumer app.
  @override
  void dispose() {
    _costController.dispose();
    _ageController.dispose();
    _lifeController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'What you can claim',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildIndemnityExplainer(),
            const SizedBox(height: 24),
            _buildCalculationDetails(),
            const SizedBox(height: 24),
            _buildCalculatedPayoutCard(),
            const SizedBox(height: 16),
            _buildWearAndTearAccordion(),
            const SizedBox(height: 32),
            _buildSubmitButton(),
            const SizedBox(height: 40),
          ],
        ),
      ),
      bottomNavigationBar: const HostBottomNav(current: HostTab.bookings),
    );
  }

  Widget _buildIndemnityExplainer() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.02),
            blurRadius: 8,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Text(
        "Insurance claims for items are calculated based on 'indemnity'. This means we consider the age of the item and its expected lifespan to ensure you are not placed in a better financial position than before the loss.",
        style: GoogleFonts.inter(
          color: GoOutsColors.body,
          fontSize: 14,
          height: 1.5,
        ),
      ),
    );
  }

  Widget _buildCalculationDetails() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Calculation Details',
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 18,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 20),
          Text(
            'Item original cost (£)',
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 14,
              fontWeight: FontWeight.w600,
            ),
          ),
          const SizedBox(height: 8),
          _buildTextField(_costController, 'e.g. 800', onChanged: (_) => _calculatePayout()),
          const SizedBox(height: 16),
          Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Item age (years)',
                      style: GoogleFonts.inter(
                        color: GoOutsColors.navy,
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    const SizedBox(height: 8),
                    _buildTextField(_ageController, '7', onChanged: (_) => _calculatePayout()),
                  ],
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Total life (years)',
                      style: GoogleFonts.inter(
                        color: GoOutsColors.navy,
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    const SizedBox(height: 8),
                    _buildTextField(_lifeController, '10', onChanged: (_) => _calculatePayout()),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildTextField(TextEditingController controller, String hint, {Function(String)? onChanged}) {
    return TextField(
      controller: controller,
      keyboardType: TextInputType.number,
      onChanged: onChanged,
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: GoogleFonts.inter(color: GoOutsColors.onSurfaceVariant.withValues(alpha: 0.5)),
        filled: true,
        fillColor: GoOutsColors.background,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        contentPadding: const EdgeInsets.all(16),
      ),
    );
  }

  Widget _buildCalculatedPayoutCard() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: const Color(0xFF00668C), // Darker teal shade from reference
        borderRadius: BorderRadius.circular(16),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Calculated Payout',
                style: GoogleFonts.inter(
                  color: Colors.white,
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                ),
              ),
              const Icon(Icons.calculate_outlined, color: Colors.white, size: 24),
            ],
          ),
          const SizedBox(height: 12),
          Text(
            '£${_calculatedPayout.toStringAsFixed(2)}',
            style: GoogleFonts.inter(
              color: Colors.white,
              fontSize: 36,
              fontWeight: FontWeight.w800,
            ),
          ),
          const SizedBox(height: 4),
          Text(
            _costController.text.isEmpty 
                ? 'Enter details above to see estimate' 
                : 'Estimated payout based on details provided',
            style: GoogleFonts.inter(
              color: Colors.white.withValues(alpha: 0.8),
              fontSize: 14,
            ),
          ),
          const SizedBox(height: 20),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.white.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(12),
            ),
            child: Text(
              "Worked example: A carpet that cost £800 and is 7 years old with a 10 year life pays £240.",
              style: GoogleFonts.inter(
                color: Colors.white,
                fontSize: 13,
                fontStyle: FontStyle.italic,
                height: 1.4,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildWearAndTearAccordion() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
      ),
      child: ExpansionTile(
        title: Text(
          'What counts as wear and tear',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 15,
            fontWeight: FontWeight.w700,
          ),
        ),
        tilePadding: EdgeInsets.zero,
        childrenPadding: const EdgeInsets.only(bottom: 16),
        iconColor: GoOutsColors.navy,
        collapsedIconColor: GoOutsColors.navy,
        children: [
          Text(
            "Ordinary wear and tear is the natural and gradual deterioration of an item from its intended use. This is not covered by insurance.",
            style: GoogleFonts.inter(color: GoOutsColors.body, fontSize: 13, height: 1.5),
          ),
        ],
      ),
    );
  }

  Widget _buildSubmitButton() {
    return ElevatedButton(
      onPressed: () {},
      style: ElevatedButton.styleFrom(
        backgroundColor: GoOutsColors.primary,
        minimumSize: const Size(double.infinity, 56),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        elevation: 0,
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            'Submit claim',
            style: GoogleFonts.inter(
              color: Colors.white,
              fontSize: 16,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(width: 12),
          const Icon(Icons.send_outlined, color: Colors.white, size: 20),
        ],
      ),
    );
  }
}
