// Generated by Google Stitch. Source folder: 9-payout_details
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';


class PayoutDetailsScreen extends StatefulWidget {
  const PayoutDetailsScreen({super.key});

  @override
  State<PayoutDetailsScreen> createState() => _PayoutDetailsScreenState();
}

class _PayoutDetailsScreenState extends State<PayoutDetailsScreen> {
  bool _agreedToHMRC = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Color(0xFF00668C)),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'How you get paid',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      body: SingleChildScrollView(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildHMRCAlert(),
            Padding(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildSectionHeader(Icons.account_balance_outlined, 'Bank account details'),
                  const SizedBox(height: 16),
                  _buildBankAccountForm(),
                  const SizedBox(height: 32),
                  _buildSectionHeader(Icons.description_outlined, 'Required by HMRC'),
                  const SizedBox(height: 16),
                  _buildHMRCForm(),
                  const SizedBox(height: 32),
                  _buildSecurityImage(),
                  const SizedBox(height: 40),
                ],
              ),
            ),
          ],
        ),
      ),
      bottomNavigationBar: _buildBottomNav(),
    );
  }

  Widget _buildHMRCAlert() {
    return Container(
      margin: const EdgeInsets.all(16),
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: const Color(0xFFA5E1F9),
        borderRadius: BorderRadius.circular(16),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: const BoxDecoration(
              color: Colors.white,
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.account_balance, color: GoOutsColors.teal, size: 24),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Reporting to HMRC',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 16,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const SizedBox(height: 8),
                Text(
                  'UK law requires platforms to report earnings data annually to HMRC. This helps ensure tax compliance for all property hosts. You will receive a copy of this reported data for your records at the end of each tax year.',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 13,
                    height: 1.5,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSectionHeader(IconData icon, String title) {
    return Row(
      children: [
        Icon(icon, color: GoOutsColors.teal, size: 22),
        const SizedBox(width: 12),
        Text(
          title,
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 16,
            fontWeight: FontWeight.w700,
          ),
        ),
      ],
    );
  }

  Widget _buildBankAccountForm() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildTextFieldLabel('Account holder name'),
          _buildTextField('As it appears on your statement'),
          const SizedBox(height: 20),
          Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildTextFieldLabel('Sort code'),
                    _buildTextField('00-00-00'),
                  ],
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildTextFieldLabel('Account number'),
                    _buildTextField('8 digits'),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildHMRCForm() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(16),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildTextFieldLabel('Full legal name'),
          _buildTextField('First name and Surname'),
          const SizedBox(height: 20),
          _buildTextFieldLabel('Home address'),
          _buildTextField('Search for address', suffixIcon: Icons.search),
          const SizedBox(height: 20),
          _buildTextFieldLabel('Date of birth'),
          // dd/mm/yyyy. Stitch produced the US order on a UK-only product —
          // and a date of birth is exactly where that ambiguity bites, because
          // 03/04/1970 is a valid date under both readings and nothing would
          // ever flag the wrong one.
          _buildTextField('dd/mm/yyyy', suffixIcon: Icons.calendar_today_outlined),
          const SizedBox(height: 20),
          _buildTextFieldLabel('National Insurance or UTR'),
          _buildTextField('NI number or 10-digit UTR'),
          const SizedBox(height: 24),
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SizedBox(
                width: 24,
                height: 24,
                child: Checkbox(
                  value: _agreedToHMRC,
                  onChanged: (val) => setState(() => _agreedToHMRC = val!),
                  activeColor: GoOutsColors.teal,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  'I confirm that the information provided is accurate and I understand it will be shared with HMRC as required by UK law.',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.body,
                    fontSize: 13,
                    height: 1.4,
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildTextFieldLabel(String label) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Text(
        label,
        style: GoogleFonts.inter(
          color: GoOutsColors.navy,
          fontSize: 13,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }

  Widget _buildTextField(String hint, {IconData? suffixIcon}) {
    return TextField(
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: GoogleFonts.inter(color: GoOutsColors.body.withValues(alpha: 0.5), fontSize: 14),
        filled: true,
        fillColor: Colors.white,
        suffixIcon: suffixIcon != null ? Icon(suffixIcon, color: const Color(0xFF94A3B8), size: 20) : null,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: GoOutsColors.border),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: GoOutsColors.border),
        ),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
      ),
    );
  }

  Widget _buildSecurityImage() {
    return ClipRRect(
      borderRadius: BorderRadius.circular(16),
      child: Stack(
        alignment: Alignment.bottomLeft,
        children: [
          Image.network(
            'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800',
            height: 200,
            width: double.infinity,
            fit: BoxFit.cover,
          ),
          Container(
            height: 200,
            width: double.infinity,
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.bottomCenter,
                end: Alignment.topCenter,
                colors: [Colors.black.withValues(alpha: 0.6), Colors.transparent],
              ),
            ),
          ),
          const Padding(
            padding: EdgeInsets.all(16.0),
            child: Text(
              'Secure UK payment processing',
              style: TextStyle(
                color: Colors.white,
                fontSize: 14,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildBottomNav() {
    return Container(
      padding: const EdgeInsets.fromLTRB(20, 20, 20, 32),
      decoration: const BoxDecoration(
        color: GoOutsColors.surface,
        border: Border(top: BorderSide(color: Color(0xFFF1F5F9), width: 1)),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          ElevatedButton(
            // ── PAYOUT SETUP IS NOT BUILT. Guarded 6 August 2026. ─────────
            //
            // This screen shows fields for account holder name, SORT CODE,
            // ACCOUNT NUMBER, full legal name, home address and date of birth
            // — and none of them have a controller. Nothing is captured and
            // nothing is saved.
            //
            // Left as it was, a host types their bank details, taps this
            // button, and leaves believing GoOuts has them. They would then
            // wait for a payout that was never set up.
            //
            // NOT FIXED BY WIRING IT TO FIRESTORE. Sort code plus account
            // number plus date of birth plus home address is an identity theft
            // kit, and bank details belong with a payment provider, never in
            // our own database. When this is built it hands off to Stripe
            // Connect onboarding, which collects them directly, and GoOuts
            // stores only the returned account id.
            //
            // Delete this guard when that exists. Do not delete the HMRC
            // agreement above it — see task #96.
            onPressed: _agreedToHMRC
                ? () => ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content: Text(
                          'Payout setup opens when payments go live. Your '
                          'property listing is saved and unaffected.',
                        ),
                        duration: Duration(seconds: 4),
                      ),
                    )
                : null,
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF00668C),
              disabledBackgroundColor: const Color(0xFF94A3B8).withValues(alpha: 0.3),
              minimumSize: const Size(double.infinity, 56),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              elevation: 0,
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  'Complete setup',
                  style: GoogleFonts.inter(
                    color: Colors.white,
                    fontSize: 16,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const SizedBox(width: 8),
                const Icon(Icons.chevron_right, color: Colors.white, size: 20),
              ],
            ),
          ),
          const SizedBox(height: 12),
          Text(
            'SECURE END-TO-END ENCRYPTION',
            style: GoogleFonts.inter(
              color: const Color(0xFF94A3B8),
              fontSize: 10,
              fontWeight: FontWeight.w700,
              letterSpacing: 1.0,
            ),
          ),
        ],
      ),
    );
  }
}
