// Generated by Google Stitch. Source folder: 3-confirm_location
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import 'host_routes.dart';

import '../../../theme/goouts_colors.dart';


class CreateListingLocationConfirmScreen extends StatelessWidget {
  const CreateListingLocationConfirmScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          // Was `leading: const Icon(...)` — a decorative arrow that
          // was NOT tappable. It looked like a back button and did
          // nothing, which is worse than having no arrow at all.
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Create Listing',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
        actions: [
          TextButton(
            onPressed: () {},
            child: Text(
              'Save & Exit',
              style: GoogleFonts.inter(
                color: GoOutsColors.primary,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          const SizedBox(width: 8),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'We filled this in for you',
              style: GoogleFonts.inter(
                color: GoOutsColors.navy,
                fontSize: 24,
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'You know things a map does not. Review the auto-detected location data below and change anything that is not right.',
              style: GoogleFonts.inter(
                color: GoOutsColors.body,
                fontSize: 15,
                height: 1.5,
              ),
            ),
            const SizedBox(height: 24),
            _buildLocationCard(
              icon: Icons.apartment,
              title: 'Distance to centre',
              content: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    '7.9 miles',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 32,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  Text(
                    'from Central London',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.body,
                      fontSize: 14,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 8),
            _buildLocationCard(
              icon: Icons.park_outlined,
              title: 'Nearby attractions',
              content: Wrap(
                spacing: 8,
                runSpacing: 8,
                children: [
                  _buildChip('Hyde Park'),
                  _buildChip('Little Venice'),
                ],
              ),
            ),
            const SizedBox(height: 8),
            _buildLocationCard(
              icon: Icons.storefront_outlined,
              title: 'GoOuts partners nearby',
              content: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    '14',
                    style: GoogleFonts.inter(
                      color: const Color(0xFF00668C),
                      fontSize: 48,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  Text(
                    'within half a mile',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.body,
                      fontSize: 14,
                    ),
                  ),
                  const SizedBox(height: 20),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      _buildPartnerCategory(Icons.coffee_outlined, 'Coffee'),
                      _buildPartnerCategory(Icons.restaurant_outlined, 'Dining'),
                      _buildPartnerCategory(Icons.local_bar_outlined, 'Pubs'),
                    ],
                  ),
                ],
              ),
            ),
            const SizedBox(height: 8),
            _buildLocationCard(
              icon: Icons.train_outlined,
              title: 'Nearest stations',
              content: Column(
                children: [
                  _buildStationRow('Paddington', '5 mins', Colors.orange),
                  _buildStationRow('Marylebone', '12 mins', Colors.brown),
                  _buildStationRow('Lancaster Gate', '15 mins', Colors.red),
                ],
              ),
            ),
            const SizedBox(height: 24),
            Row(
              children: [
                const Icon(Icons.info_outline, color: GoOutsColors.body, size: 16),
                const SizedBox(width: 8),
                Text(
                  'Data from OpenStreetMap contributors',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.body,
                    fontSize: 12,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 32),
            ElevatedButton(
              onPressed: () =>
                  Navigator.of(context).pushNamed(HostRoutes.newDetails),
              style: ElevatedButton.styleFrom(
                backgroundColor: GoOutsColors.primary,
                minimumSize: const Size(double.infinity, 52),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                elevation: 0,
              ),
              child: Text(
                'Confirm & Continue',
                style: GoogleFonts.inter(
                  color: Colors.white,
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }

  Widget _buildLocationCard({
    required IconData icon,
    required String title,
    required Widget content,
  }) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Stack(
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                padding: const EdgeInsets.all(10),
                decoration: const BoxDecoration(
                  color: GoOutsColors.tint,
                  shape: BoxShape.circle,
                ),
                child: Icon(icon, color: GoOutsColors.teal, size: 24),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      title,
                      style: GoogleFonts.inter(
                        color: GoOutsColors.navy,
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    const SizedBox(height: 12),
                    content,
                  ],
                ),
              ),
            ],
          ),
          const Positioned(
            top: 0,
            right: 0,
            child: Icon(Icons.edit_outlined, color: Colors.black26, size: 20),
          ),
        ],
      ),
    );
  }

  Widget _buildChip(String label) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(
        color: GoOutsColors.tint,
        borderRadius: BorderRadius.circular(20),
      ),
      child: Text(
        label,
        style: GoogleFonts.inter(
          color: GoOutsColors.navy,
          fontSize: 13,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }

  Widget _buildPartnerCategory(IconData icon, String label) {
    return Column(
      children: [
        Icon(icon, color: GoOutsColors.teal, size: 24),
        const SizedBox(height: 4),
        Text(
          label,
          style: GoogleFonts.inter(
            color: GoOutsColors.body,
            fontSize: 12,
            fontWeight: FontWeight.w500,
          ),
        ),
      ],
    );
  }

  Widget _buildStationRow(String name, String time, Color color) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Row(
        children: [
          Icon(Icons.circle, color: color, size: 8),
          const SizedBox(width: 12),
          Text(
            name,
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 14,
              fontWeight: FontWeight.w600,
            ),
          ),
          const Spacer(),
          Row(
            children: [
              const Icon(Icons.directions_walk, color: GoOutsColors.body, size: 14),
              const SizedBox(width: 4),
              Text(
                time,
                style: GoogleFonts.inter(
                  color: GoOutsColors.body,
                  fontSize: 13,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
