// Generated by Google Stitch. Source folder: 17-make_a_claim
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';

import 'host_bottom_nav.dart';


class MakeClaimScreen extends StatefulWidget {
  const MakeClaimScreen({super.key});

  @override
  State<MakeClaimScreen> createState() => _MakeClaimScreenState();
}

class _MakeClaimScreenState extends State<MakeClaimScreen> {
  String _selectedRoom = 'Living Room';
  final TextEditingController _descriptionController = TextEditingController();
  final TextEditingController _amountController = TextEditingController();


  // Added on import, 4 August 2026. Stitch does not generate dispose().
  //
  // A TextEditingController holds a listener list and is not garbage collected
  // while the framework still references it. Without this, every push of this
  // screen leaks — and iOS kills this app for memory with no stack trace, which
  // has already happened once on the consumer app.
  @override
  void dispose() {
    _descriptionController.dispose();
    _amountController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.navy),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Make a claim',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildWindowAlert(),
            const SizedBox(height: 24),
            _buildSectionTitle('Select a room'),
            const SizedBox(height: 12),
            _buildRoomSelector(),
            const SizedBox(height: 24),
            _buildSectionTitle('Describe the damage'),
            const SizedBox(height: 12),
            _buildDescriptionField(),
            const SizedBox(height: 24),
            _buildSectionTitle('Estimated amount'),
            const SizedBox(height: 12),
            _buildAmountField(),
            const SizedBox(height: 24),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                _buildSectionTitle('Attach evidence'),
                TextButton(
                  onPressed: () {},
                  child: Text(
                    'Capture list photos',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.primary,
                      fontWeight: FontWeight.w600,
                      fontSize: 13,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 8),
            _buildEvidenceGrid(),
            const SizedBox(height: 100),
          ],
        ),
      ),
      bottomNavigationBar: const HostBottomNav(current: HostTab.bookings),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
      floatingActionButton: _buildSubmitButton(),
    );
  }

  Widget _buildWindowAlert() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFFFFE4E1).withValues(alpha: 0.5),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: GoOutsColors.error.withValues(alpha: 0.1)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.timer_outlined, color: GoOutsColors.error, size: 24),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  '72-hour window remaining',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.error,
                    fontSize: 15,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  'You have 72 hours from checkout to claim.',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy.withValues(alpha: 0.7),
                    fontSize: 13,
                  ),
                ),
                const SizedBox(height: 4),
                RichText(
                  text: TextSpan(
                    style: GoogleFonts.inter(color: GoOutsColors.navy, fontSize: 13),
                    children: const [
                      TextSpan(text: 'Time remaining: '),
                      TextSpan(
                        text: '64h 12m',
                        style: TextStyle(fontWeight: FontWeight.w700),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: GoogleFonts.inter(
        color: GoOutsColors.navy,
        fontSize: 16,
        fontWeight: FontWeight.w700,
      ),
    );
  }

  Widget _buildRoomSelector() {
    final rooms = [
      {'name': 'Living Room', 'image': 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&q=80&w=200'},
      {'name': 'Kitchen', 'image': 'https://images.unsplash.com/photo-1556911223-e27021882721?auto=format&fit=crop&q=80&w=200'},
      {'name': 'Master Bed', 'image': 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=200'},
    ];

    return SizedBox(
      height: 120,
      child: ListView.separated(
        scrollDirection: Axis.horizontal,
        itemCount: rooms.length,
        separatorBuilder: (context, index) => const SizedBox(width: 12),
        itemBuilder: (context, index) {
          final room = rooms[index];
          final isSelected = _selectedRoom == room['name'];
          return GestureDetector(
            onTap: () => setState(() => _selectedRoom = room['name']!),
            child: Container(
              width: 130,
              decoration: BoxDecoration(
                color: GoOutsColors.surface,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(
                  color: isSelected ? GoOutsColors.primary : Colors.transparent,
                  width: 2,
                ),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withValues(alpha: 0.03),
                    blurRadius: 4,
                    offset: const Offset(0, 2),
                  ),
                ],
              ),
              child: Column(
                children: [
                  Expanded(
                    child: ClipRRect(
                      borderRadius: const BorderRadius.vertical(top: Radius.circular(10)),
                      child: Image.network(
                        room['image']!,
                        width: double.infinity,
                        fit: BoxFit.cover,
                      ),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.symmetric(vertical: 8),
                    child: Text(
                      room['name']!,
                      style: GoogleFonts.inter(
                        color: GoOutsColors.navy,
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }

  Widget _buildDescriptionField() {
    return Container(
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
      ),
      child: TextField(
        controller: _descriptionController,
        maxLines: 4,
        decoration: InputDecoration(
          hintText: 'Please provide factual details regarding the nature and extent of the damage observed...',
          hintStyle: GoogleFonts.inter(color: GoOutsColors.onSurfaceVariant, fontSize: 14),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide.none,
          ),
          contentPadding: const EdgeInsets.all(16),
        ),
      ),
    );
  }

  Widget _buildAmountField() {
    return Container(
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
      ),
      child: TextField(
        controller: _amountController,
        keyboardType: TextInputType.number,
        decoration: InputDecoration(
          prefixText: '£ ',
          prefixStyle: GoogleFonts.inter(color: GoOutsColors.navy, fontWeight: FontWeight.w500),
          hintText: '0.00',
          hintStyle: GoogleFonts.inter(color: GoOutsColors.onSurfaceVariant),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide.none,
          ),
          contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
        ),
      ),
    );
  }

  Widget _buildEvidenceGrid() {
    final images = [
      'https://images.unsplash.com/photo-1581850518616-bcb8188c4436?auto=format&fit=crop&q=80&w=200',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=200',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=200',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&q=80&w=200',
      'https://images.unsplash.com/photo-1556911223-e27021882721?auto=format&fit=crop&q=80&w=200',
    ];

    return GridView.builder(
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 3,
        crossAxisSpacing: 8,
        mainAxisSpacing: 8,
      ),
      itemCount: images.length + 1,
      itemBuilder: (context, index) {
        if (index < images.length) {
          return Stack(
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(8),
                child: Image.network(
                  images[index],
                  width: double.infinity,
                  height: double.infinity,
                  fit: BoxFit.cover,
                ),
              ),
              if (index == 0)
                Center(
                  child: Container(
                    padding: const EdgeInsets.all(4),
                    decoration: const BoxDecoration(color: Colors.white, shape: BoxShape.circle),
                    child: const Icon(Icons.check_circle_outline, color: GoOutsColors.primary, size: 20),
                  ),
                ),
            ],
          );
        } else {
          return Container(
            decoration: BoxDecoration(
              border: Border.all(color: GoOutsColors.onSurfaceVariant.withValues(alpha: 0.3), width: 1),
              borderRadius: BorderRadius.circular(8),
            ),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Icon(Icons.add_a_photo_outlined, color: GoOutsColors.onSurfaceVariant, size: 24),
                const SizedBox(height: 4),
                Text(
                  'New Photo',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.onSurfaceVariant,
                    fontSize: 10,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ],
            ),
          );
        }
      },
    );
  }

  Widget _buildSubmitButton() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16.0),
      child: ElevatedButton(
        onPressed: () {},
        style: ElevatedButton.styleFrom(
          backgroundColor: GoOutsColors.primary,
          minimumSize: const Size(double.infinity, 56),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          elevation: 0,
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              'Continue to claim details',
              style: GoogleFonts.inter(
                color: Colors.white,
                fontSize: 16,
                fontWeight: FontWeight.w600,
              ),
            ),
            const SizedBox(width: 8),
            const Icon(Icons.chevron_right, color: Colors.white),
          ],
        ),
      ),
    );
  }
}
