// Generated by Google Stitch. Source folder: 4-property_details
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import 'host_routes.dart';

import '../../../theme/goouts_colors.dart';


class PropertyDetailsScreen extends StatefulWidget {
  const PropertyDetailsScreen({super.key});

  @override
  State<PropertyDetailsScreen> createState() => _PropertyDetailsScreenState();
}

class _PropertyDetailsScreenState extends State<PropertyDetailsScreen> {
  String _selectedType = 'Apartment';
  int _bedrooms = 1;
  int _beds = 1;
  int _bathrooms = 1;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          // Was `leading: const Icon(...)` — a decorative arrow that
          // was NOT tappable. It looked like a back button and did
          // nothing, which is worse than having no arrow at all.
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Create Listing',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
        actions: [
          TextButton(
            onPressed: () {},
            child: Text(
              'Save & Exit',
              style: GoogleFonts.inter(
                color: GoOutsColors.primary,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          const SizedBox(width: 8),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'What best describes your property?',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 24,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Select the type that most closely matches your space.',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.body,
                      fontSize: 15,
                    ),
                  ),
                  const SizedBox(height: 24),
                  _buildPropertyTypeGrid(),
                  const SizedBox(height: 32),
                  Text(
                    'How many rooms are available?',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.navy,
                      fontSize: 22,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Accurate details help guests know what to expect.',
                    style: GoogleFonts.inter(
                      color: GoOutsColors.body,
                      fontSize: 15,
                    ),
                  ),
                  const SizedBox(height: 24),
                  _buildCounterSection(),
                  const SizedBox(height: 32),
                  _buildCaptureRequirementsInfo(),
                ],
              ),
            ),
          ),
          _buildFooter(),
        ],
      ),
    );
  }

  Widget _buildPropertyTypeGrid() {
    final types = [
      {'name': 'Apartment', 'icon': Icons.apartment},
      {'name': 'House', 'icon': Icons.home_outlined},
      {'name': 'Townhouse', 'icon': Icons.bungalow_outlined},
      {'name': 'Unique Space', 'icon': Icons.star_border},
    ];

    return GridView.builder(
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        crossAxisSpacing: 12,
        mainAxisSpacing: 12,
        childAspectRatio: 1.3,
      ),
      itemCount: types.length,
      itemBuilder: (context, index) {
        final type = types[index];
        final isSelected = _selectedType == type['name'];
        return GestureDetector(
          onTap: () => setState(() => _selectedType = type['name'] as String),
          child: Container(
            decoration: BoxDecoration(
              color: isSelected ? GoOutsColors.tint : GoOutsColors.surface,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: isSelected ? GoOutsColors.primary : Colors.black12,
                width: isSelected ? 2 : 1,
              ),
            ),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(
                  type['icon'] as IconData,
                  color: isSelected ? GoOutsColors.navy : GoOutsColors.navy.withValues(alpha: 0.7),
                  size: 32,
                ),
                const SizedBox(height: 12),
                Text(
                  type['name'] as String,
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 15,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  Widget _buildCounterSection() {
    return Container(
      decoration: BoxDecoration(
        color: GoOutsColors.surface,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.black12),
      ),
      child: Column(
        children: [
          _buildCounterRow(
            icon: Icons.bed_outlined,
            label: 'Bedrooms',
            count: _bedrooms,
            onChanged: (val) => setState(() => _bedrooms = val),
          ),
          const Divider(height: 1, indent: 56),
          _buildCounterRow(
            icon: Icons.hotel_outlined,
            label: 'Beds',
            count: _beds,
            onChanged: (val) => setState(() => _beds = val),
          ),
          const Divider(height: 1, indent: 56),
          _buildCounterRow(
            icon: Icons.bathtub_outlined,
            label: 'Bathrooms',
            count: _bathrooms,
            onChanged: (val) => setState(() => _bathrooms = val),
          ),
        ],
      ),
    );
  }

  Widget _buildCounterRow({
    required IconData icon,
    required String label,
    required int count,
    required ValueChanged<int> onChanged,
  }) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
      child: Row(
        children: [
          Icon(icon, color: GoOutsColors.navy, size: 24),
          const SizedBox(width: 16),
          Expanded(
            child: Text(
              label,
              style: GoogleFonts.inter(
                color: GoOutsColors.navy,
                fontSize: 16,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
          Row(
            children: [
              _buildRoundButton(
                icon: Icons.remove,
                onTap: count > 0 ? () => onChanged(count - 1) : null,
              ),
              const SizedBox(width: 16),
              SizedBox(
                width: 24,
                child: Text(
                  count.toString(),
                  textAlign: TextAlign.center,
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 18,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              const SizedBox(width: 16),
              _buildRoundButton(
                icon: Icons.add,
                onTap: () => onChanged(count + 1),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildRoundButton({required IconData icon, VoidCallback? onTap}) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.all(8),
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          border: Border.all(color: Colors.black12),
          color: onTap == null ? Colors.black.withValues(alpha: 0.02) : Colors.transparent,
        ),
        child: Icon(
          icon,
          size: 20,
          color: onTap == null ? Colors.black26 : GoOutsColors.navy,
        ),
      ),
    );
  }

  Widget _buildCaptureRequirementsInfo() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: GoOutsColors.tint.withValues(alpha: 0.5),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: GoOutsColors.primary.withValues(alpha: 0.1)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.camera_alt_outlined, color: GoOutsColors.primary, size: 24),
              const SizedBox(width: 12),
              Expanded(
                child: Text(
                  'Your guests will be asked to photograph:',
                  style: GoogleFonts.inter(
                    color: GoOutsColors.navy,
                    fontSize: 16,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          _buildRequirementItem('Living Room (Standard)'),
          _buildRequirementItem('Kitchen (Standard)'),
          ...List.generate(_bedrooms, (index) => _buildRequirementItem('Bedroom ${index + 1}')),
          ...List.generate(_bathrooms, (index) => _buildRequirementItem('Bathroom ${index + 1}')),
        ],
      ),
    );
  }

  Widget _buildRequirementItem(String label) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Row(
        children: [
          Container(
            width: 6,
            height: 6,
            decoration: const BoxDecoration(color: GoOutsColors.primary, shape: BoxShape.circle),
          ),
          const SizedBox(width: 12),
          Text(
            label,
            style: GoogleFonts.inter(
              color: GoOutsColors.body,
              fontSize: 14,
              fontWeight: FontWeight.w500,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildFooter() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: const BoxDecoration(
        color: GoOutsColors.surface,
        border: Border(top: BorderSide(color: Colors.black12, width: 0.5)),
      ),
      child: SafeArea(
        child: Row(
          children: [
            TextButton(
              onPressed: () {},
              child: Text(
                'Back',
                style: GoogleFonts.inter(
                  color: GoOutsColors.primary,
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
            const Spacer(),
            ElevatedButton(
              onPressed: () =>
                  Navigator.of(context).pushNamed(HostRoutes.newAmenities),
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF00668C),
                minimumSize: const Size(140, 52),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                elevation: 0,
              ),
              child: Text(
                'Next',
                style: GoogleFonts.inter(
                  color: Colors.white,
                  fontSize: 16,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
