// Generated by Google Stitch. Source folder: 21-host_help
// Imported and renamed 4 August 2026. See
// goouts/design/SHORT_STAY_HOST_WIRING_PLAN.md
//
// NOT WIRED. Every handler in this file is still empty and every
// figure on screen is placeholder copy from Stitch. Do not read a
// number here as real data.
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../theme/goouts_colors.dart';


class HelpCentreScreen extends StatelessWidget {
  const HelpCentreScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: GoOutsColors.background,
      appBar: AppBar(
        backgroundColor: GoOutsColors.surface,
        elevation: 0.5,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: GoOutsColors.primary),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: Text(
          'Help Centre',
          style: GoogleFonts.inter(
            color: GoOutsColors.navy,
            fontSize: 20,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.symmetric(vertical: 24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _buildSearchBar(),
            const SizedBox(height: 24),
            _buildCategorySection('Getting started', [
              _buildHelpItem(Icons.rocket_launch_outlined, 'How it works'),
              _buildHelpItem(Icons.verified_user_outlined, 'Verification'),
            ]),
            _buildCategorySection('Your listing', [
              _buildHelpItem(Icons.camera_alt_outlined, 'Photos'),
              _buildHelpItem(Icons.payments_outlined, 'Pricing'),
              _buildHelpItem(Icons.pool, 'Amenities'),
            ]),
            _buildCategorySection('Bookings', [
              _buildHelpItem(Icons.check_circle_outline, 'Accepting'),
              _buildHelpItem(Icons.cancel_outlined, 'Declining'),
              _buildHelpItem(Icons.policy_outlined, 'Policies'),
            ]),
            _buildCategorySection('Arrival and departure', [
              _buildHelpItem(Icons.inventory_2_outlined, 'The capture pack'),
              _buildHelpItem(Icons.vpn_key_outlined, 'Key exchange'),
            ]),
            _buildCategorySection('Damage claims', [
              _buildHelpItem(Icons.handyman_outlined, 'Wear and tear'),
              _buildHelpItem(Icons.timer_outlined, 'The 72-hour rule'),
            ]),
            _buildCategorySection('Getting paid', [
              _buildHelpItem(Icons.access_time, 'Payout timings'),
              _buildHelpItem(Icons.account_balance_outlined, 'HMRC reporting'),
            ]),
            _buildCategorySection('Rules and registration', [
              _buildHelpItem(Icons.nightlight_outlined, 'Local night limits'),
              _buildHelpItem(Icons.shield_outlined, 'Safety duties'),
            ]),
            const SizedBox(height: 40),
          ],
        ),
      ),
      bottomNavigationBar: _buildBottomButton(),
    );
  }

  Widget _buildSearchBar() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16.0),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16),
        decoration: BoxDecoration(
          color: GoOutsColors.surface,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: GoOutsColors.border),
        ),
        child: TextField(
          decoration: InputDecoration(
            icon: const Icon(Icons.search, color: GoOutsColors.onSurfaceVariant),
            hintText: 'Search help articles',
            hintStyle: GoogleFonts.inter(color: GoOutsColors.onSurfaceVariant, fontSize: 14),
            border: InputBorder.none,
          ),
        ),
      ),
    );
  }

  Widget _buildCategorySection(String title, List<Widget> items) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.fromLTRB(16, 8, 16, 12),
          child: Text(
            title,
            style: GoogleFonts.inter(
              color: GoOutsColors.primary,
              fontSize: 15,
              fontWeight: FontWeight.w700,
            ),
          ),
        ),
        Container(
          margin: const EdgeInsets.symmetric(horizontal: 16),
          decoration: BoxDecoration(
            color: GoOutsColors.surface,
            borderRadius: BorderRadius.circular(12),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withValues(alpha: 0.02),
                blurRadius: 10,
                offset: const Offset(0, 4),
              ),
            ],
          ),
          child: Column(
            children: items,
          ),
        ),
        const SizedBox(height: 16),
      ],
    );
  }

  Widget _buildHelpItem(IconData icon, String label) {
    return Column(
      children: [
        ListTile(
          contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
          leading: Icon(icon, color: GoOutsColors.primary, size: 22),
          title: Text(
            label,
            style: GoogleFonts.inter(
              color: GoOutsColors.navy,
              fontSize: 15,
              fontWeight: FontWeight.w600,
            ),
          ),
          trailing: const Icon(Icons.chevron_right, color: GoOutsColors.onSurfaceVariant, size: 20),
          onTap: () {},
        ),
        if (label != 'Verification' && 
            label != 'Amenities' && 
            label != 'Policies' && 
            label != 'Key exchange' && 
            label != 'The 72-hour rule' && 
            label != 'HMRC reporting' && 
            label != 'Safety duties')
          const Divider(height: 1, color: Color(0xFFF1F5F9), indent: 54),
      ],
    );
  }

  Widget _buildBottomButton() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: const BoxDecoration(
        color: GoOutsColors.surface,
        border: Border(top: BorderSide(color: Color(0xFFEDF2F7), width: 1)),
      ),
      child: SafeArea(
        child: ElevatedButton.icon(
          onPressed: () {},
          icon: const Icon(Icons.headset_mic_outlined, color: Colors.white, size: 20),
          label: Text(
            'Contact support',
            style: GoogleFonts.inter(
              color: Colors.white,
              fontSize: 16,
              fontWeight: FontWeight.w700,
            ),
          ),
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF00668C), // Darker teal from brand
            minimumSize: const Size(double.infinity, 56),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            elevation: 0,
          ),
        ),
      ),
    );
  }
}
