import Flutter
import UIKit
import FirebaseAuth
import FirebaseCore

// ─────────────────────────────────────────────────────────────────────────────
//  THE reCAPTCHA CALLBACK ARRIVES HERE, NOT IN AppDelegate.
//
//  Written 8 August 2026. This file was empty:
//
//      class SceneDelegate: FlutterSceneDelegate { }
//
//  ── WHY AN EMPTY FILE WAS THE BUG ──────────────────────────────────────────
//
//  This app is UIScene-based. Info.plist declares UIApplicationSceneManifest
//  with a UISceneDelegateClassName pointing at this class.
//
//  On a scene-based iOS app, `application(_:open:options:)` on the APP
//  delegate is NOT CALLED for an incoming URL. iOS delivers it to
//  `scene(_:openURLContexts:)` on the SCENE delegate instead.
//
//  That single routing difference is the whole reported fault. Firebase Phone
//  Auth falls back to a reCAPTCHA web view when the silent APNs push does not
//  arrive; on completion it re-opens the app through the REVERSED_CLIENT_ID
//  URL scheme registered in Info.plist. The URL arrived, iOS brought the app
//  forward — and with nothing implemented here, it was dropped on the floor.
//
//  The host solves the reCAPTCHA and the screen never moves. No error, no log,
//  nothing in Crashlytics. Identical symptom to a hung network call, which is
//  why it is easy to spend a long time looking in the wrong place.
//
//  ⚠ IF THIS FILE IS EVER REGENERATED BY `flutter create`, THIS COMES BACK.
//  Same class of gap as the missing NSCameraUsageDescription that terminated
//  the app on the selfie screen: a template file that is complete as a
//  template and incomplete for what this app does.
//
//  ── BOTH DELEGATES IMPLEMENT IT, ON PURPOSE ────────────────────────────────
//
//  AppDelegate keeps its own copy. Flutter's scene support is recent and which
//  delegate receives the URL has moved between versions. Handing the same URL
//  to Auth.auth().canHandle twice is harmless — it either claims it or it does
//  not. Handing it to neither is a frozen screen.
// ─────────────────────────────────────────────────────────────────────────────

class SceneDelegate: FlutterSceneDelegate {

  // ⚠ Every Auth.auth() below is guarded. Build 8 crashed on launch because
  // AppDelegate touched Auth before firebase_core had configured the default
  // app — see the long note in AppDelegate.swift. willConnectTo runs even
  // earlier than that did, so the same mistake is even easier to make here.
  private var firebaseReady: Bool { FirebaseApp.app() != nil }

  /// The app was already running and a URL brought it forward. This is the
  /// path the reCAPTCHA return takes in practice.
  override func scene(_ scene: UIScene,
                      openURLContexts URLContexts: Set<UIOpenURLContext>) {
    for context in URLContexts {
      if firebaseReady, Auth.auth().canHandle(context.url) {
        // Claimed by Firebase Auth — do not pass it on. Letting it continue to
        // super means the plugin registry also tries to route a URL that has
        // already been consumed.
        return
      }
    }
    super.scene(scene, openURLContexts: URLContexts)
  }

  /// The app was NOT running and was launched by the URL. Rarer for reCAPTCHA
  /// — the app is normally alive behind the web view — but it happens when iOS
  /// has evicted it for memory, which this app has form for.
  override func scene(_ scene: UIScene,
                      willConnectTo session: UISceneSession,
                      options connectionOptions: UIScene.ConnectionOptions) {
    super.scene(scene, willConnectTo: session, options: connectionOptions)

    // ⚠ firebaseReady is nearly always FALSE here — this runs during launch,
    // before the Flutter engine has registered firebase_core. Unguarded, this
    // line crashes the app on any URL-triggered cold launch. It is written to
    // skip rather than crash; AppDelegate's handler picks the URL up once the
    // engine is alive.
    for context in connectionOptions.urlContexts {
      if firebaseReady, Auth.auth().canHandle(context.url) { return }
    }
  }
}
