// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkNmBP1FgJNUnGSKeCmOEGGOCT1nPiHjE',
    appId: '1:289872853637:web:7461195d14c1f92b5bc7ec',
    messagingSenderId: '289872853637',
    projectId: 'goouts-f16db',
    authDomain: 'goouts-f16db.firebaseapp.com',
    databaseURL: 'https://goouts-f16db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'goouts-f16db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8x5e2Qbm5ccOHnSc4RJpLNQ57Bo3y0sk',
    appId: '1:289872853637:android:3a08b3c0ec88526b5bc7ec',
    messagingSenderId: '289872853637',
    projectId: 'goouts-f16db',
    databaseURL: 'https://goouts-f16db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'goouts-f16db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0u_n7kV2uPuSKFjaqYOyEiioDR5Y5d9o',
    appId: '1:289872853637:ios:472beb4e0b11c1625bc7ec',
    messagingSenderId: '289872853637',
    projectId: 'goouts-f16db',
    databaseURL: 'https://goouts-f16db-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'goouts-f16db.firebasestorage.app',
    androidClientId: '289872853637-3rs6veqhalq00hm7oc2iicstp9dnhnd3.apps.googleusercontent.com',
    iosClientId: '289872853637-t9dd60rkgm1dugr9vdqt2ubgslh0gi3l.apps.googleusercontent.com',
    iosBundleId: 'com.goouts.host',
  );
}
